---
# TODO: Users probably also need to be crated via plain LDAP ldapsearch -x -LLL -h ip -D "cn=Directory Manager" -w "{{ ldap_admin_password }}" -s sub '(alias={{ user.name ~ '@' ~ mailserver_domain }})'
- name: Find the user by uid
  community.general.ldap_search:
    dn: "uid={{ user.name }}"
    server_uri: ldap://127.0.0.1/
    bind_dn: "cn=Directory Manager"
    bind_pw: "{{ ldap_admin_password }}"
  register: kolab_user_entry
- name: Display user entry
  ansible.builtin.debug:
    var: kolab_user_entry
- name: Find the user by e-mail alias
  community.general.ldap_search:
    dn: "alias={{ user.name ~ '@' ~ mailserver_domain }}"
    server_uri: ldap://127.0.0.1/
    bind_dn: "cn=Directory Manager"
    bind_pw: "{{ ldap_admin_password }}"
  register: kolab_user_entry
- name: Display user entry
  ansible.builtin.debug:
    var: kolab_user_entry
- name: Delete old user LDAP entry
  community.general.ldap_entry:
    dn: "alias={{ user.name ~ '@' ~ mailserver_domain }}"
    server_uri: ldap://127.0.0.1/
    bind_dn: "cn=Directory Manager"
    bind_pw: "{{ ldap_admin_password }}"
    state: absent
- name: Set user attributes
  ansible.builtin.set_fact:
    ldap_user_attributes: |
      {% for alias in [user.name ~ '@' ~ mailserver_domain] + user.aliases %}
      alias: {{ alias }}
      {% endfor %}
      givenName: {{ user.firstname | default(user.name) }}
      loginShell: /bin/bash
      sn: {{ user.surname | default(default_surname) }}
      homeDirectory: /home/{{ user.name }}
      mail: {{ user.name ~ '@' ~ mailserver_domain }}
      objectClass: inetorgperson
      objectClass: kolabinetorgperson
      objectClass: mailrecipient
      objectClass: organizationalperson
      objectClass: person
      objectClass: posixaccount
      objectClass: top
- name: Create new LDAP entry
  community.general.ldap_entry:
    dn: "alias={{ user.name ~ '@' ~ mailserver_domain }}"
    server_uri: ldap://127.0.0.1/
    bind_dn: "cn=Directory Manager"
    bind_pw: "{{ ldap_admin_password }}"
    attributes: "{{ ldap_user_attributes }}"
