---
- name: "Create restart directories for {{ service }}" # noqa name[template] we need to be informative, even if we deviate from the standards
  ansible.builtin.file:
    state: directory
    path: "/etc/systemd/system/{{ service }}.service.d"
    mode: u=rwX,og=rX
    owner: root
    group: root
- name: "Deploy restart files for {{ service }}" # noqa name[template] we need to be informative, even if we deviate from the standards
  ansible.builtin.copy:
    src: systemd/restart.conf
    dest: "/etc/systemd/system/{{ service }}.service.d/restart.conf"
    mode: u=rw,og=r
    backup: yes
    owner: root
    group: root
  notify: "Restart {{ service }}"
