- name: "Set DNSMASQ config for {{ current_domain }}"
  lineinfile:
    path: /etc/dnsmasq.conf
    line: "{{ item }}"
    mode: u=rw,og=r
    owner: root
    group: dnsmasq
    state: present
    backup: yes
  loop:
    - "server=/{{ current_domain }}/{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    - "server=/{{ current_domain }}/{{ hostvars[inventory_hostname]['ansible_default_ipv6']['address'] }}"
    - "host-record={{ current_domain }},{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }},{{ hostvars[inventory_hostname]['ansible_default_ipv6']['address'] }},{{ hostvars[inventory_hostname]['ansible_default_ipv4']['interface'] }}"
    - "cname={{ mailserver_hostname }}.{{ mailserver_domain.split('.')[0] }}.{{ current_domain }},ns.{{ current_domain }},{{ current_domain }}"
    - "mx-host={{ current_domain }},{{ mailserver_hostname }}.{{ mailserver_domain }},1"
    - "mx-host=mail.{{ current_domain }},{{ mailserver_hostname }}.{{ mailserver_domain }},1"
    - "mx-host=mail2.{{ current_domain }},{{ mailserver_hostname }}.{{ mailserver_domain }},5"
    - "mx-host=smtp.{{ current_domain }},{{ mailserver_hostname }}.{{ mailserver_domain }},10"
    - 'txt-record={{ current_domain }},"v=spf1 mx ~all"'
    - 'txt-record=_dmarc.{{ current_domain }},"v=DMARC1; p=none; pct=100; rua=mailto:dmarc-reports@{{ current_domain }}; ruf=mailto:dmarc-reports@{{ current_domain }}"'
