- name: "Upload {{ mariadb_database }} DB schema"
  copy:
    src: "mariadb/{{ mariadb_database }}_schema.sql"
    dest: "/tmp/ansible-mailserver-install.{{ mariadb_database }}_schema.sql"
- name: "Create {{ mariadb_database }} DB schema"
  mysql_db:
    name: "{{ mariadb_database }}"
    state: "{{ mariadb_state|default('present') }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    target: "{{ '/tmp/ansible-mailserver-install.' ~ mariadb_database ~ '_schema.sql' if mariadb_state is defined and mariadb_state == 'import' }}"
  no_log: yes
