- name: Configure local DNS cache
  nmcli:
    conn_name: ens192
    ip4: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    dns4:
      - 127.0.0.1
      - 8.8.8.8
      - 1.1.1.1
    state: present
    type: ethernet
- name: Make sure BIND and NetworkManager are running
  systemd:
    name: named
    daemon_reload: yes
    enabled: yes
    state: restarted
- name: Reload DNS cache
  command: rndc reload
- name: Create resolved.conf.d directory
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: u=rwX,og=rX
- name: Create named log directory
  file:
    path: /var/log/named
    state: directory
    owner: named
    group: named
    mode: u=rwX,og=rX
- name: Set up logging for fail2ban
  lineinfile:
    path: /etc/named.conf
    insertafter: 'logging {'
    line: '        channel security_file {file "/var/log/named/security.log" versions 3 size 30m;severity dynamic;print-time yes;};category security {security_file;};'
    regex: 'security_file'
    mode: u=rw,g=r
    owner: root
    group: named
    state: present
    backup: yes
    create: yes
- name: Enable local DNS caching
  blockinfile:
    path: /etc/systemd/resolved.conf.d/LocalDNSCache.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK Local DNS cache"
    block: |
      [Resolve]
      Cache=yes
      # CacheFromLocalhost=yes
      Domains={% for custom_domain in [mailserver_domain] + custom_domains %}{{ custom_domain }} {% if loop.index != loop.length %} {% endif %}{% endfor %}
      DNS=127.0.0.1 8.8.8.8 1.1.1.1
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
- name: Make sure resolved is running
  systemd:
    name: systemd-resolved
    daemon_reload: yes
    enabled: yes
    state: restarted
