---
- name: Open firewall
  ansible.builtin.import_tasks:: firewall.yml
  vars:
    port: dns # noqa var-naming[no-reserved] we refer to a port here, so I call it a port
  when: 'public_dns == "yes"'
- name: Configure local DNS cache
  ansible.builtin.import_tasks:: local_dns_cache.yml
- name: Configure PowerDNS
  ansible.builtin.import_tasks:: pdns.yml
- name: Set up DNS records
  ansible.builtin.import_tasks:: dns_records.yml
- name: Configure PowerDNS recursor
  ansible.builtin.import_tasks:: pdns_recursor.yml
- name: Configure DNSDist
  ansible.builtin.import_tasks:: dnsdist.yml
- name: Make sure PowerDNS is running
  ansible.builtin.systemd_service:
    name: pdns
    daemon_reload: yes
    enabled: yes
    state: started
  when: 'public_dns == "yes"'
- name: Make sure PowerDNS recursor is running
  ansible.builtin.systemd_service:
    name: pdns-recursor
    daemon_reload: yes
    enabled: yes
    state: started
- name: Make sure DNSDist is running
  ansible.builtin.systemd_service:
    name: dnsdist
    daemon_reload: yes
    enabled: yes
    state: started
  when: 'public_dns == "yes"'
- name: Configure PowerAdmin
  ansible.builtin.import_tasks:: poweradmin.yml
  tags:
    - dyndns
    - poweradmin
