- name: Open firewall
  include: firewall.yml
  vars:
    port: dns
  when: 'public_dns == "yes"'
- name: Configure local DNS cache
  include: local_dns_cache.yml
- name: Configure PowerDNS
  include: pdns.yml
- name: Set up DNS records
  include: dns_records.yml
- name: Configure PowerDNS recursor
  include: pdns_recursor.yml
- name: Configure DNSDist
  include: dnsdist.yml
- name: Make sure PowerDNS is running
  systemd:
    name: pdns
    daemon_reload: yes
    enabled: yes
    state: started
  when: 'public_dns == "yes"'
- name: Make sure PowerDNS recursor is running
  systemd:
    name: pdns-recursor
    daemon_reload: yes
    enabled: yes
    state: started
- name: Make sure DNSDist is running
  systemd:
    name: dnsdist
    daemon_reload: yes
    enabled: yes
    state: started
  when: 'public_dns == "yes"'
- name: Configure PowerAdmin
  include: poweradmin.yml
