---
- name: Open firewall
  import_tasks: firewall.yml
  vars:
    port: dns
  when: 'public_dns == "yes"'
- name: Configure local DNS cache
  import_tasks: local_dns_cache.yml
- name: Configure PowerDNS
  import_tasks: pdns.yml
- name: Set up DNS records
  import_tasks: dns_records.yml
- name: Configure PowerDNS recursor
  import_tasks: pdns_recursor.yml
- name: Configure DNSDist
  import_tasks: dnsdist.yml
- name: Make sure PowerDNS is running
  ansible.builtin.systemd_service:
    name: pdns
    daemon_reload: yes
    enabled: yes
    state: started
  when: 'public_dns == "yes"'
- name: Make sure PowerDNS recursor is running
  ansible.builtin.systemd_service:
    name: pdns-recursor
    daemon_reload: yes
    enabled: yes
    state: started
- name: Make sure DNSDist is running
  ansible.builtin.systemd_service:
    name: dnsdist
    daemon_reload: yes
    enabled: yes
    state: started
  when: 'public_dns == "yes"'
- name: Configure PowerAdmin
  import_tasks: poweradmin.yml
  tags:
    - dyndns
    - poweradmin
