---
- name: Configure DNSDist
  ansible.builtin.template:
    src: dnsdist/dnsdist.conf.j2
    dest: /etc/dnsdist/dnsdist.conf
    backup: yes
    owner: dnsdist
    group: dnsdist
    mode: u=rw,g=r,o=
  when: 'public_dns == "yes"'
  notify: Restart dnsdist
