- name: Open firewall
  include: firewall.yml
  vars:
    port: "{{ item }}"
  loop:
    - imap
    - imaps
    - pop3
    - pop3s
- name: Automatically restart services
  include: autorestart.yml
  vars:
    service: dovecot
- name: Configure Dovecot protocols
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    regexp: '^protocols ='
    line: 'protocols = imap pop3 lmtp'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
- name: Configure Dovecot Authentication Mechanism
  lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { key: "auth_debug", value: "yes" }
    - { key: "auth_debug_passwords", value: "yes" }
    - { key: "disable_plaintext_auth", value: "yes" }
    - { key: "auth_username_format", value: "%u" }
    - { key: "auth_mechanisms", value: "plain login" }
- name: Configure Dovecot SSL
  lineinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { key: "ssl", value: "required" }
    - { key: "ssl_cert", value: "</etc/letsencrypt/live/{{ mailserver_domain }}/fullchain.pem" }
    - { key: "ssl_key", value: "</etc/letsencrypt/live/{{ mailserver_domain }}/privkey.pem" }
    - { key: "ssl_dh", value: "</etc/letsencrypt/dh.pem" }
    - { key: "ssl_min_protocol", value: "TLSv1.2" }
    - { key: "ssl_prefer_server_ciphers", value: "yes" }
- name: Add Dovecot user to the mail and apache groups
  user:
    name: dovecot
    groups: mail,apache
    append: yes
- name: Upload complex Dovecot configs
  copy:
    dest: "/etc/dovecot/conf.d/{{ item }}"
    src: "dovecot/{{ item }}"
    mode: u=rw,og=r
    backup: yes
    owner: root
    group: root
  loop:
    - 10-mail.conf
    - 10-master.conf
    - 15-mailboxes.conf
    - 15-lda.conf
    - 20-imap.conf
    - 20-lmtp.conf
    - 90-sieve.conf
- name: Render Dovecot config templates
  template:
    src: "dovecot/{{ item }}.j2"
    dest: "/etc/dovecot/{{ item }}"
    mode: u=rw,og=r
    owner: root
    group: root
    backup: yes
  loop:
    - dovecot-sql.conf.ext
    - report-ham.sieve
    - report-spam.sieve
- name: Configure Dovecot auth extensions
  lineinfile:
    regexp: '{{ item.line }}'
    line: "{{ '#' if item.comment }}{{ item.line }}"
    path: /etc/dovecot/conf.d/10-auth.conf
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { comment: false, line: "!include auth-sql.conf.ext"}
    - { comment: true, line: "!include auth-system.conf.ext"}
- name: Restore old imap account
  command: 'doveadm -o imapc_features="rfc822.size fetch-headers" -o imapc_host={{ item.old_imap_mail.host }} -o imapc_ssl={{ item.old_imap_mail.ssl|default("imaps") }} -o imapc_ssl_verify={{ item.old_imap_mail.ssl_verify|default("yes") }} -o imapc_port={{ item.old_imap_mail.port|default(993)|string }} -o imapc_user={{ item.old_imap_mail.user }} -o imapc_password={{ item.old_imap_mail.password }} sync -1 -Ru {{ item.name }}@{{ mailserver_domain }} imapc:'
  when: "{{ item.old_imap_mail is defined }}"
  loop: "{{ users }}"
- name: Sync old imap account
  cron:
    name: Sync old imap account
    special_time: hourly
    job: 'doveadm -o imapc_features="rfc822.size fetch-headers" -o imapc_host={{ item.old_imap_mail.host }} -o imapc_ssl={{ item.old_imap_mail.ssl|default("imaps") }} -o imapc_ssl_verify={{ item.old_imap_mail.ssl_verify|default("yes") }} -o imapc_port={{ item.old_imap_mail.port|default(993)|string }} -o imapc_user={{ item.old_imap_mail.user }} -o imapc_password={{ item.old_imap_mail.password }} sync -1 -Ru {{ item.name }}@{{ mailserver_domain }} imapc:'
    backup: yes
    user: "{{ item.name }}"
  when: "{{ item.old_imap_mail is defined and item.old_imap_mail.sync is defined and item.old_imap_mail.sync }}"
  loop: "{{ users }}"
