---
- name: Open firewall
  include_tasks: firewall.yml
  vars:
    port: "{{ item }}"
  loop:
    - imap
    - imaps
    - pop3
    - pop3s
- name: Automatically restart services
  import_tasks: autorestart.yml
  vars:
    service: dovecot
- name: Configure Dovecot protocols
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    regexp: '^protocols ='
    line: 'protocols = imap pop3 lmtp'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  notify: Restart dovecot
- name: Configure Dovecot Authentication Mechanism
  lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { key: "auth_debug", value: "yes" }
    - { key: "auth_debug_passwords", value: "yes" }
    - { key: "disable_plaintext_auth", value: "yes" }
    - { key: "auth_username_format", value: "%u" }
    - { key: "auth_mechanisms", value: "plain login" }
  notify: Restart dovecot
- name: Configure Dovecot SSL
  lineinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { key: "ssl", value: "required" }
    - { key: "ssl_cert", value: "</etc/letsencrypt/certificates/{{ mailserver_domain }}.pem" }
    - { key: "ssl_key", value: "</etc/letsencrypt/certificates/{{ mailserver_domain }}.key" }
    - { key: "ssl_dh", value: "</etc/letsencrypt/dh.pem" }
    - { key: "ssl_min_protocol", value: "TLSv1.2" }
    - { key: "ssl_prefer_server_ciphers", value: "yes" }
  notify: Restart dovecot
- name: Add Dovecot user to the mail and apache groups
  user:
    name: dovecot
    groups: mail,apache
    append: yes
- name: Upload complex Dovecot configs
  ansible.builtin.copy:
    dest: "/etc/dovecot/conf.d/{{ item }}"
    src: "dovecot/{{ item }}"
    mode: u=rw,og=r
    backup: yes
    owner: root
    group: root
  loop:
    - 10-mail.conf
    - 10-master.conf
    - 15-mailboxes.conf
    - 15-lda.conf
    - 20-imap.conf
    - 20-lmtp.conf
    - 90-sieve.conf
  notify: Restart dovecot
- name: Render Dovecot config templates
  template:
    src: "dovecot/{{ item }}.j2"
    dest: "/etc/dovecot/{{ item }}"
    mode: u=rw,og=r
    owner: root
    group: root
    backup: yes
  loop:
    - dovecot-sql.conf.ext
    - report-ham.sieve
    - report-spam.sieve
  notify: Restart dovecot
- name: Configure Dovecot auth extensions
  lineinfile:
    regexp: '{{ item.line }}'
    line: "{{ '#' if item.comment }}{{ item.line }}"
    path: /etc/dovecot/conf.d/10-auth.conf
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { comment: false, line: "!include auth-sql.conf.ext"}
    - { comment: true, line: "!include auth-system.conf.ext"}
  notify: Restart dovecot
- name: Make sure Dovecot is running
  ansible.builtin.systemd_service:
    name: dovecot
    daemon_reload: yes
    enabled: yes
    state: restarted
