---
- name: Create custom fail2ban filters
  copy:
    src: "fail2ban/{{ item }}"
    dest: "/etc/fail2ban/filter.d/{{ item }}"
  loop:
    - postfixadmin.conf
    # - dnsmasq.conf
  notify: Restart fail2ban
- name: Enable fail2ban jails
  blockinfile:
    path: /etc/fail2ban/jail.d/ansible-mailserver.local
    marker: "# {mark} ANSIBLE MANAGED BLOCK ansible-mailserver fail2ban jails"
    block: |
      [DEFAULT]
      ignoreip = 127.0.0.1/8, ::1

      [sshd]
      enabled  = true

      [selinux-ssh]
      enabled  = true

      [apache-auth]
      enabled  = true

      [apache-badbots]
      enabled  = true

      [apache-noscript]
      enabled  = true

      [apache-overflows]
      enabled  = true

      [apache-nohome]
      enabled  = true

      [apache-botsearch]
      enabled  = true

      [apache-fakegooglebot]
      enabled  = true

      [apache-modsecurity]
      enabled  = true

      [apache-shellshock]
      enabled  = true

      [php-url-fopen]
      enabled  = true

      [horde]
      enabled  = true

      # [vsftpd]
      # enabled  = true

      [postfix]
      enabled  = true

      [postfix-rbl]
      enabled  = true

      [sendmail-auth]
      enabled  = true

      [sendmail-reject]
      enabled  = true

      [dovecot]
      enabled  = true

      [sieve]
      enabled  = true

      [postfix-sasl]
      enabled  = true

      [mysqld-auth]
      enabled  = true

      # [mongodb-auth]
      # enabled  = true

      [pam-generic]
      enabled  = true

      # [slapd]
      # enabled  = true

      [postfixadmin]
      enabled  = true
      port     = http,https
      filter   = postfixadmin
      logpath  = /var/log/php-fpm/www-error.log
      findtime = 60
      maxretry = 3
      bantime  = 120

      # [dnsmasq]
      # enabled = true
      # port     = 53
      # action   = %(banaction)s[name=%(__name__)s-tcp, port="%(port)s", protocol="tcp", chain="%(chain)s", actname=%(banaction)s-tcp]
      #            %(banaction)s[name=%(__name__)s-udp, port="%(port)s", protocol="udp", chain="%(chain)s", actname=%(banaction)s-udp]
      # logpath = /var/log/messages
      # findtime = 60
      # maxretry = 42
      # bantime = 3600
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
  notify: Restart fail2ban
