- name: Fill default DNS records
  include_tasks: add_dns_record.yml
  vars:
    record:
      zone: "{{ zone }}"
      name: "{{ item.name ~ '.' ~ zone ~ '.' }}"
      ttl: "{{ item.ttl|default('3600') }}"
      type: "{{ item.type }}"
      content: "{{ item.content }}"
  become: yes
  become_user: pdns
  loop: "{{ default_dns_records + [{ name: mailserver_hostname ~ '.',	type: 'CNAME', content: zone ~ '.'}] if if zone == mailserver_domain }}"

- name: Fill default CNAME records
  include_tasks: add_dns_record.yml
  vars:
    record:
      zone: "{{ zone }}"
      name: "{{ item.name ~ '.' ~ zone ~ '.' }}"
      ttl: "3600"
      type: "{{ item.type }}"
      content: "{{ item.content }}"
  become: yes
  become_user: pdns
  loop:
    - { name: "*.", type: "CNAME", content: "{{ zone }}"}
    - { name: "ns.", type: "CNAME", content: "{{ zone }}"}
