---
- name: "Render {{ mariadb_database.db }} data"
  template:
    src: "mariadb/{{ mariadb_database.db }}.sql.j2"
    dest: "/tmp/ansible-mailserver-install.{{ mariadb_database.db }}_data.sql"
    mode: u=rw,og=r
    owner: root
    group: root
    backup: yes
- name: "Fill {{ mariadb_database.db }} DB"
  mysql_db:
    name: "{{ mariadb_database.db }}"
    state: import
    login_user: "{{ mariadb_database.user }}"
    login_password: "{{ mariadb_database.password }}"
    target: "/tmp/ansible-mailserver-install.{{ mariadb_database.db }}_data.sql"
  no_log: yes
