- name: "Open Firewall for {{ port }}"
  block:
    - name: "Open firewall for numeric port {{ port }}"
      firewalld:
        port : "{{ port }}"
        permanent: yes
        state: enabled
        immediate: yes
      notify: Restart systemd service
        vars:
          service_to_restart: firewalld
  rescue:
    - name: "Open firewall for service {{ port }}"
      firewalld:
        service: "{{ port }}"
        permanent: yes
        state: enabled
        immediate: yes
      notify: Restart systemd service
        vars:
          service_to_restart: firewalld
