---
- name: Ensure firewall is enabled
  ansible.builtin.systemd_service:
    name: firewalld
    daemon_reload: yes
    enabled: yes
    state: started
- name: "Open Firewall for {{ port }}" # noqa name[template] we need to be informative, even if we deviate from the standards
  block:
    - name: "Open firewall for numeric port {{ port }}"
      firewalld:
        port : "{{ port }}"
        permanent: yes
        state: enabled
        immediate: yes
      notify: Restart firewalld
  rescue:
    - name: "Open firewall for service {{ port }}"
      firewalld:
        service: "{{ port }}"
        permanent: yes
        state: enabled
        immediate: yes
      notify: Restart firewalld
