- name: Open firewall
  include: firewall.yml
  vars:
    port: 989-990/tcp
- name: Make sure vsftpd is running
  systemd:
    name: vsftpd
    daemon_reload: yes
    enabled: yes
    state: restarted
