---
- name: Increase upload size and execution time
  lineinfile:
    path: '{{ item.file }}'
    regexp: '^{{ item.key }} ='
    line: '{{ item.key }} = {{ item.value }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { file: '/etc/php.ini', key: 'upload_max_filesize', value: '50M' }
    # - { file: '/etc/opt/remi/php56/php.ini', key: 'upload_max_filesize', value: '50M' }
    - { file: '/etc/opt/remi/php74/php.ini', key: 'upload_max_filesize', value: '50M' }
    # - { file: '/etc/opt/remi/php81/php.ini', key: 'upload_max_filesize', value: '50M' }
    - { file: '/etc/php.ini', key: 'post_max_size', value: '50M' }
    # - { file: '/etc/opt/remi/php56/php.ini', key: 'post_max_size', value: '50M' }
    - { file: '/etc/opt/remi/php74/php.ini', key: 'post_max_size', value: '50M' }
    # - { file: '/etc/opt/remi/php81/php.ini', key: 'post_max_size', value: '50M' }
    - { file: '/etc/php.ini', key: 'max_execution_time', value: '300' }
    # - { file: '/etc/opt/remi/php56/php.ini', key: 'max_execution_time', value: '300' }
    - { file: '/etc/opt/remi/php74/php.ini', key: 'max_execution_time', value: '300' }
    # - { file: '/etc/opt/remi/php81/php.ini', key: 'max_execution_time', value: '300' }
  notify: Restart php-fpm
- name: Upload complex Horde configs
  copy:
    dest: "/etc/horde/{{ item }}/conf.php"
    src: "horde/{{ item }}/conf.php"
    mode: u=rw
    backup: yes
    owner: apache
    group: apache
  loop:
    - imp
    - ingo
    - kronolith
    - mnemo
    - nag
    - passwd
    - turba
    - wicked
- name: Render Horde config templates
  template:
    src: "horde/{{ item.app }}/conf.php.j2"
    dest: "/etc/horde/{{ item.app }}/conf.php"
    mode: "{{ item.mode }}"
    owner: apache
    group: apache
    backup: yes
  loop:
    - { app: '', mode: 'ug=rw' }
    # - { app: 'kronolith', mode: 'u=rw' }
- name: Create horde DB schema
  import_tasks: create_mariadb_schema.yml
  vars:
    mariadb_database: horde
    mariadb_state: "{{ ('import' if reset == 'yes')|default('present') }}"
- name: Set up Horde DB privileges
  community.mysql.mysql_user:
    name: hordeuser
    password: '{{ horde_db_password }}'
    priv: 'horde.*:ALL'
    host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Generate Horde DB schema
  command: horde-db-migrate
- name: Enable ActiveSync
  mysql_query:
    login_db: horde
    login_user: hordeuser
    login_password: '{{ horde_db_password }}'
    query:
      - REPLACE INTO `horde_perms` (`perm_id`, `perm_name`, `perm_parents`, `perm_data`) VALUES (3,'wicked',NULL,'a:2:{s:4:\"type\";s:6:\"matrix\";s:7:\"default\";i:14;}'),(4,'wicked:pages',':3','a:1:{s:4:\"type\";s:6:\"matrix\";}'),(5,'wicked:pages:AllPages',':3:4','a:1:{s:4:\"type\";s:6:\"matrix\";}'),(6,'horde',NULL,'a:1:{s:4:\"type\";s:6:\"matrix\";}'),(7,'horde:activesync',':6','a:2:{s:4:\"type\";s:7:\"boolean\";s:7:\"default\";b:1;}'),(8,'horde:activesync:provisioning',':6:7','a:3:{s:4:\"type\";s:4:\"enum\";s:6:\"params\";a:1:{i:0;a:4:{i:0;s:0:\"\";s:4:\"true\";s:6:\"Enable\";s:5:\"allow\";s:31:\"Allow non-provisionable devices\";s:5:\"false\";s:25:\"Disable (not recommended)\";}}s:7:\"default\";s:5:\"allow\";}');
  no_log: yes
- name: Fetch themes
  unarchive:
    src: http://eph.dk/horde-addons/5.2/combined-1.0.0.zip
    dest: /tmp
    remote_src: yes
- name: Install themes
  shell: 'echo -e "/usr/share/horde\nroot\nroot\n755\n644\nYes\n"|./install.sh'
  args:
    chdir: /tmp/combined-1.0.0
