- name: Update PEAR repo
  command: pear channel-update pear.php.net
- name: Get source for Horde packages
  block:
    - name: Refresh Horde PEAR repo
      command: pear channel-update pear.horde.org
  rescue:
    - name: Enable the Horde PEAR repository
      command: pear channel-discover pear.horde.org
- name: Install Horde role
  pear:
    name: horde/horde_role
    state: present
- name: Set Horde install directory
  shell: 'echo /var/www/html/horde | pear run-scripts horde/horde_role'
- name: Install Horde extensions
  pear:
    name: "{{ item }}"
    state: present
  loop:
    - pear/Net_FTP, pear/Cache, pear/DB, pear/SOAP-beta, pear/XML_Serializer-beta
    # - pear/HTTP_Request, pear/DB, Services_Weather
    - Net_DNS2, File_Fstab, http, horde/horde, horde/horde_lz4
    - pecl/memcache
    - pecl/imagick
