- name: Increase upload size to 50MiB
  lineinfile:
    path: /etc/php.ini
    regexp: '^upload_max_filesize ='
    line: 'upload_max_filesize = 50M'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
- name: Upload complex Horde configs
  copy:
    dest: "/etc/horde/{{ item }}/conf.php"
    src: "horde/{{ item }}/conf.php"
    mode: u=rw
    backup: yes
    owner: apache
    group: apache
  loop:
    - imp
    - ingo
    - kronolith
    - mnemo
    - nag
    - passwd
    - turba
    - wicked
- name: Render Horde config templates
  template:
    src: "horde/{{ item.app }}/conf.php.j2"
    dest: "/etc/horde/{{ item.app }}/conf.php"
    mode: "{{ item.mode }}"
    owner: apache
    group: apache
    backup: yes
  loop:
    - { app: '', mode: 'ug=rw' }
    # - { app: 'kronolith', mode: 'u=rw' }
- name: Create horde DB schema
  include_tasks: create_mariadb_schema.yml
  vars:
    mariadb_database: horde
- name: Set up Horde DB privileges
  mysql_user:
    name: hordeuser
    password: '{{ horde_db_password }}'
    priv: 'horde.*:ALL'
    host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Generate Horde DB schema
  command: horde-db-migrate
- name: Fetch themes
  unarchive:
    src: http://eph.dk/horde-addons/5.2/combined-1.0.0.zip
    dest: /tmp
    remote_src: yes
- name: Install themes
  shell: 'echo -e "/usr/share/horde\nroot\nroot\n755\n644\nYes\n"|./install.sh'
  args:
    chdir: /tmp/combined-1.0.0
