---
- name: Configure local DNS cache
  nmcli:
    conn_name: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['interface'] }}"
    ip4: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    ip6: "{{ hostvars[inventory_hostname]['ansible_default_ipv6']['address'] }}"
    dns4:
      - 127.0.0.1
      - 8.8.8.8
      - 1.1.1.1
    dns6:
      - ::1
      - 2001:4860:4860::8888
      - 2606:4700:4700::1111
    state: present
    type: ethernet
  notify: Restart NetworkManager
- name: Create resolved.conf.d directory
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: u=rwX,og=rX
- name: Enable local DNS caching
  blockinfile:
    path: /etc/systemd/resolved.conf.d/LocalDNSCache.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK Local DNS cache"
    block: |
      [Resolve]
      Cache=yes
      # CacheFromLocalhost=yes
      Domains={% for custom_domain in [mailserver_domain] + custom_domains %}{{ custom_domain }} {% if loop.index != loop.length %} {% endif %}{% endfor %}

      DNS=127.0.0.1 ::1 8.8.8.8 2001:4860:4860::8888 1.1.1.1 2606:4700:4700::1111
      DNSStubListener=No
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
  notify: Restart systemd-resolved
- name: Make sure resolved is running
  systemd:
    name: systemd-resolved
    daemon_reload: yes
    enabled: yes
    state: started
