---
# tasks file for ansible-mailserver
- name: Generate passwords if they don't exist yet
  set_fact:
    postfixadmin_db_password: "{{ postfixadmin_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.postfixadmin_db_password chars=ascii_letters,digits')) }}"
    horde_db_password: "{{ horde_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.horde_db_password chars=ascii_letters,digits')) }}"
    mysql_root_password: "{{ mysql_root_password | default(lookup('password', '/tmp/ansible-mailserver-install.mysql_root_password chars=ascii_letters,digits')) }}"
    ldap_admin_password: "{{ ldap_admin_password | default(lookup('password', '/tmp/ansible-mailserver-install.ldap_admin_password chars=ascii_letters,digits')) }}"
    mariabackup_password: "{{ mariabackup_password | default(lookup('password', '/tmp/ansible-mailserver-install.mariabackup_password chars=ascii_letters,digits')) }}"
    horde_secret_key: "{{ horde_secret_key | default(lookup('password', '/tmp/ansible-mailserver-install.horde_secret_key chars=ascii_letters,digits')) }}"
  no_log: yes
- name: Fill authorized submit user list
  set_fact:
    authorized_submit_users: "{{ authorized_submit_users + [ item.name ] }}"
  loop: "{{ users }}"
  no_log: yes
- name: Create backup directory
  file:
    path: /backup
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: u=rwX
- name: Configure OS
  include: os.yml
- name: Configure fail2ban
  include: fail2ban.yml
- name: Configure DNS caching
  include: dns.yml
- name: Configure MariaDB
  include: mariadb.yml
- name: Configure PostfixAdmin
  include: postfixadmin.yml
- name: Set up SSL
  include: ssl.yml
- name: Configure LDAP
  include: ldap.yml
- name: Set up Horde
  include: horde.yml
- name: Set up ElasticSearch
  include: elasticsearch.yml
- name: Set up FTP
  include: ftp.yml
- name: Configure Apache
  include: httpd.yml
- name: Configure Postfix
  include: postfix.yml
- name: Configure Dovecot
  include: dovecot.yml
- name: Set up DKIM
  include: dkim.yml
- name: Set up DMARC
  include: dmarc.yml
- name: Set up SPAMAssassin
  include: spamassassin.yml
- name: Set up MongoDB
  include: mongodb.yml
- name: Set up backups
  include: backups.yml
- name: Enable systemd services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: restarted
  loop:
    - firewalld
    - fail2ban
    - postfix
    - httpd
    - dovecot
    - mariadb
    - php-fpm
    - opendkim
    - opendmarc
    - postgrey
    - named
    - NetworkManager
    - spamassassin
    - spamass-milter
    - vsftpd
    - elasticsearch
    - "dirsrv@{{ mailserver_hostname.split('.')[0] }}"
    - mongod
