---
# tasks file for ansible-mailserver
- name: Generate passwords if they don't exist yet
  set_fact:
    postfixadmin_password: "{{ postfixadmin_password | default(lookup('password', '/tmp/postfixadmin_password chars=ascii_letters,digits,punctuation')) }}"
    mysql_root_password: "{{ mysql_root_password | default(lookup('password', '/tmp/mysql_root_password chars=ascii_letters,digits,punctuation')) }}"
- name: Fill authorized submit user list
  set_fact:
    authorized_submit_users: "{{ authorized_submit_users + [ item.name ] }}"
  loop: "{{ users }}"
- name: Configure OS
  include: os.yml
- name: Configure Apache
  include: httpd.yml
- name: Set up SSL
  include: ssl.yml
- name: Configure Postfix
  include: postfix.yml
- name: Configure Dovecot
  include: dovecot.yml
- name: Configure MariaDB
  include: mariadb.yml
- name: Configure PostfixAdmin
  include: postfixadmin.yml
- name: Set up DKIM
  include: dkim.yml
- name: Set up DMARC
  include: dmarc.yml
- name: Set up SPAMAssassin
  include: spamassassin.yml
- name: Set up Horde
  include: horde.yml
- name: Enable systemd services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: restarted
  loop:
    - firewalld
    - postfix
    - httpd
    - dovecot
    - mariadb
    - php-fpm
    - opendkim
    - opendmarc
    - postgrey
    - named
    - NetworkManager
    - spamassassin
    - spamass-milter
- name: Read DKIM keys
  command: "cat /etc/opendkim/keys/{{ item }}/{{ dkim_selector }}.txt"
  loop: "{{ [mailserver_domain] + custom_domains }}"
  register: dkim_keys
- name: Display DKIM keys
  debug:
    msg: "{{ item.stdout }}"
  loop: "{{ dkim_keys.results }}"
