---
# tasks file for ansible-mailserver
- name: Gather facts
  setup:
- name: Generate passwords if they don't exist yet
  ansible.builtin.set_fact:
    postfixadmin_db_password: "{{ postfixadmin_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.postfixadmin_db_password chars=ascii_letters,digits')) }}"
    horde_db_password: "{{ horde_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.horde_db_password chars=ascii_letters,digits')) }}"
    powerdns_db_password: "{{ powerdns_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.powerdns_db_password chars=ascii_letters,digits')) }}"
    powerdns_api_key: "{{ powerdns_api_key | default(lookup('password', '/tmp/ansible-mailserver-install.powerdns_api_key chars=ascii_letters,digits')) }}"
    mysql_root_password: "{{ mysql_root_password | default(lookup('password', '/tmp/ansible-mailserver-install.mysql_root_password chars=ascii_letters,digits')) }}"
    ldap_admin_password: "{{ ldap_admin_password | default(lookup('password', '/tmp/ansible-mailserver-install.ldap_admin_password chars=ascii_letters,digits')) }}"
    mariabackup_password: "{{ mariabackup_password | default(lookup('password', '/tmp/ansible-mailserver-install.mariabackup_password chars=ascii_letters,digits')) }}"
    horde_secret_key: "{{ horde_secret_key | default(lookup('password', '/tmp/ansible-mailserver-install.horde_secret_key chars=ascii_letters,digits')) }}"
  no_log: yes
  tags: always
- name: Fill authorized submit user list
  ansible.builtin.set_fact:
    authorized_submit_users: "{{ authorized_submit_users + [item.name] }}"
  loop: "{{ users }}"
  no_log: yes
  tags: always
- name: Configure OS
  ansible.builtin.import_tasks:: os.yml
  tags: os
- name: Configure MariaDB
  ansible.builtin.import_tasks:: mariadb.yml
  tags: mariadb
- name: Configure DNS
  ansible.builtin.import_tasks:: dns.yml
  tags:
    - dns
    - poweradmin
    - dyndns
- name: Configure PostfixAdmin
  ansible.builtin.import_tasks:: postfixadmin.yml
  tags: postfixadmin
- name: Set up SSL
  ansible.builtin.import_tasks:: ssl.yml
  tags: ssl
- name: Configure LDAP
  ansible.builtin.import_tasks:: ldap.yml
  tags: ldap
- name: Set up Horde
  ansible.builtin.import_tasks:: horde.yml
  tags: horde
- name: Set up ElasticSearch
  ansible.builtin.import_tasks:: elasticsearch.yml
  tags: elasticsearch
- name: Set up FTP
  ansible.builtin.import_tasks:: ftp.yml
  tags: ftp
- name: Configure Apache
  ansible.builtin.import_tasks:: httpd.yml
  tags:
    - httpd
    - dyndns
    - horde
    - postfixadmin
    - poweradmin
    - wireguard
    - webdav
- name: Set up SPAMAssassin
  ansible.builtin.import_tasks:: spamassassin.yml
  tags: spamassassin
- name: Configure Antivirus
  ansible.builtin.import_tasks:: antivirus.yml
  tags: antivirus
- name: Configure Redis
  ansible.builtin.import_tasks:: redis.yml
  tags: redis
- name: Configure Postfix
  ansible.builtin.import_tasks:: postfix.yml
  tags: postfix
- name: Configure Dovecot
  ansible.builtin.import_tasks:: dovecot.yml
  tags: dovecot
- name: Sync old IMAP account
  ansible.builtin.include_tasks: imapsync.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: current_user
  vars:
    current_user: "{{ current_user }}"
  no_log: yes
  tags: imapsync
- name: Set up DKIM
  ansible.builtin.import_tasks:: dkim.yml
  tags: dkim
- name: Set up DMARC
  ansible.builtin.import_tasks:: dmarc.yml
  tags: dmarc
- name: Set up MongoDB
  ansible.builtin.import_tasks:: mongodb.yml
  tags: mongodb
- name: Set up WebDav
  ansible.builtin.import_tasks:: webdav.yml
  tags: webdav
- name: Set up WireGuard
  ansible.builtin.import_tasks:: wireguard.yml
  tags:
    - wireguard
    - dyndns
    - poweradmin
    - postfixadmin
- name: Set up backups
  ansible.builtin.import_tasks:: backups.yml
  tags: backup
- name: Configure fail2ban
  ansible.builtin.import_tasks:: fail2ban.yml
  tags: fail2ban
