---
# tasks file for ansible-mailserver
- name: Set hostname
  command: "hostnamectl set-hostname {{ mailserver_hostname }}"
- name: "Set up Remi repository"
  dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    disable_gpg_check: yes
- name: Reset the PHP DNF module
  command: dnf module reset php -y
- name: Enable the Remi PHP DNF module
  command: dnf module enable php:remi-7.4 -y
- name: Install packages
  package:
    name:
      - postfix
      - mailx
      - epel-release
      - certbot
      - httpd
      - python3-certbot-apache
      - dovecot
      - mariadb-server
      - mariadb
      - python3-mysqlclient
      - wget
      - tar
      - php-fpm
      - php-imap
      - php-mbstring
      - php-mysqlnd
      - php-gd
      - php-opcache
      - php-json
      - php-curl
      - php-zip
      - php-xml
      - php-bz2
      - php-intl
      - php-gmp
      - binutils
      - rpm-build
      - setools-console
      - policycoreutils-python3
      - policycoreutils-devel
    state: present
- name: Configure postfix
  command: 'postconf -e "{{ item }}"'
  loop:
    - "inet_interfaces = all"
    - "myhostname = {{ mailserver_hostname }}"
    - "mydomain = {{ mailserver_domain }}"
    - "myorigin = {{ mailserver_domain }}"
    - "mydestination = {{ mailserver_domain }}, $myhostname, localhost.$mydomain, localhost"
    - "message_size_limit = 52428800"
    - "mailbox_size_limit = 0"
    - "smtpd_tls_cert_file = /etc/letsencrypt/live/{{ mailserver_hostname }}/fullchain.pem"
    - "smtpd_tls_key_file = /etc/letsencrypt/live/{{ mailserver_hostname }}/privkey.pem"
    - "smtpd_tls_loglevel = 1"
    - "smtp_tls_loglevel = 1"
- name: Open firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - smtp
    - http
    - https
    - smtp-submission
    - smtps
    - imap
    - imaps
    - pop3
    - pop3s
- name: Create restart directories
  file:
    state: directory
    path: "/etc/systemd/system/{{ item }}.service.d"
    mode: u=rwX,og=rX
    owner: root
    group: root
  loop:
    - postfix
    - dovecot
- name: Deploy restart files
  copy:
    src: restart.conf
    dest: "/etc/systemd/system/{{ item }}.service.d/restart.conf"
    mode: u=rw,og=r
    backup: yes
    owner: root
    group: root
  loop:
    - postfix
    - dovecot
- name: Request Let's Encrypt certificates
  command: "certbot certonly -a apache --agree-tos --staple-ocsp --email {{ mailserver_admin_email }} -d {{ item }}"
  args:
    creates: "/etc/letsencrypt/live/{{ item }}"
  loop:
    - "{{ mailserver_hostname }}"
    - "postfixadmin.{{ mailserver_domain }}"
- name: Deploy complex Postfix configs
  copy:
    src: postfix.master.cf
    dest: /etc/postfix/master.cf
    mode: u=rw,og=r
    backup: yes
    owner: root
    group: root
- name: Configure main.cf
  lineinfile:
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
    path: /etc/postfix/main.cf
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { key: "smtpd_tls_mandatory_protocols", value: "!SSLv2, !SSLv3, !TLSv1, !TLSv1.1" }
    - { key: "smtpd_tls_protocols", value: "!SSLv2, !SSLv3, !TLSv1, !TLSv1.1" }
    - { key: "smtp_tls_mandatory_protocols", value: "!SSLv2, !SSLv3, !TLSv1, !TLSv1.1" }
    - { key: "smtp_tls_protocols", value: "!SSLv2, !SSLv3, !TLSv1, !TLSv1.1" }
    - { key: "mailbox_transport", value: "lmtp:unix:private/dovecot-lmtp" }
    - { key: "smtputf8_enable", value: "no" }
- name: Configure Dovecot protocols
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    regexp: '^protocols ='
    line: 'protocols = imap pop3 lmtp'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
- name: Configure Dovecot Maildir
  lineinfile:
    path: /etc/dovecot/conf.d/10-mail.conf
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - {key: "mail_location", value: "maildir:~/Maildir"}
    - {key: "mail_privileged_group", value: "mail"}
- name: Configure Dovecot Authentication Mechanism
  lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { key: "disable_plaintext_auth", value: "yes" }
    - { key: "auth_username_format", value: "%n" }
    - { key: "auth_mechanisms", value: "plain login" }
- name: Configure Dovecot SSL
  lineinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop:
    - { key: "ssl", value: "required" }
    - { key: "ssl_cert", value: "</etc/letsencrypt/live/{{ mailserver_hostname }}/fullchain.pem" }
    - { key: "ssl_key", value: "</etc/letsencrypt/live/{{ mailserver_hostname }}/privkey.pem" }
    - { key: "ssl_dh", value: "/etc/dovecot/dh.pem" }
    - { key: "ssl_min_protocol", value: "TLSv1.2" }
    - { key: "ssl_prefer_server_ciphers", value: "yes" }
- name: Generate OpenSSL DHParam
  openssl_dhparam:
    path: /etc/dovecot/dh.pem
    size: 4096
    mode: u=rw,og=r
    backup: yes
    owner: root
    group: root
- name: Add Dovecot user to the mail group
  user:
    name: dovecot
    groups: mail,apache
    append: yes
- name: Upload complex Dovecot configs
  copy:
    dest: "/etc/dovecot/conf.d/{{ item }}"
    src: "dovecot.{{ item }}"
    mode: u=rw,og=r
    backup: yes
    owner: root
    group: root
  loop:
    - 10-master.conf
    - 15-mailboxes.conf
- name: Set up mail aliases
  lineinfile:
    path: /etc/aliases
    regexp: '^root: *{{ mailserver_admin_user }}'
    line: 'root: {{ mailserver_admin_user }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
- name: Create OS users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512')| default(lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,punctuation')) }}"
    state: present
  loop: "{{ users }}"
- name: Apply mail aliases
  command: newaliases
- name: Auto-renew certificates
  cron:
    name: certbot
    special_time: daily
    job: "certbot renew --quiet && systemctl reload postfix dovecot httpd"
- name: Set MariaDB root password
  block:
    - name: Sets the MariaDB root password
      mysql_user: user=root password="{{ mysql_root_password }}" host=localhost
      no_log: yes
  rescue:
    - name: Ensures the MariaDB root password
      mysql_user: user=root password="{{ mysql_root_password }}" host=localhost login_user=root login_password="{{ mysql_root_password }}"
      no_log: yes
- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user:
    user: ""
    host: "{{ ansible_fqdn }}"
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Deletes anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Secures the MySQL root user for IPV6 localhost (::1)
  mysql_user:
    user: root
    password: "{{ mysql_root_password }}"
    host: "::1"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user:
    user: root
    password: "{{ mysql_root_password }}"
    host: 127.0.0.1
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user:
    user: root
    password: "{{ mysql_root_password }}"
    host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Secures the MySQL root user for server_hostname domain
  mysql_user:
    user: root
    password: "{{ mysql_root_password }}"
    host: "{{ ansible_fqdn }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Unpack postfixadmin
  unarchive:
    src: https://github.com/postfixadmin/postfixadmin/archive/postfixadmin-3.3.10.tar.gz
    dest: /var/www/
    remote_src: yes
- name: Rename postfixadmin directory
  command: mv /var/www/postfixadmin-postfixadmin-3.3.10 /var/www/postfixadmin
- name: Set up postfixadmin permissions
  file:
    path: /var/www/postfixadmin/templates_c
    state: directory
    setype: httpd_sys_rw_content_t
    recurse: yes
- name: Set postfixadmin ACLs
  acl:
    path: "{{ item.path }}"
    entity: "{{ item.entity }}"
    etype: "{{ item.etype }}"
    permissions: "{{ item.permissions }}"
    state: present
    recursive: yes
  loop:
    - { path: "/var/www/postfixadmin/templates_c", entity: "apache", etype: "user", permissions: "rwx"}
    - { path: "/etc/letsencrypt/live", entity: "apache", etype: "user", permissions: "rx"}
    - { path: "/etc/letsencrypt/archive", entity: "apache", etype: "user", permissions: "rx"}
- name: To check SELinux status
  shell: getenforce
  register: getenforce
- name: Set up SELinux rules
  when: "{{ getenforce.stdout != 'Disabled' }}"
  block:
    - name: Set SELinux booleans
      seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop:
        - httpd_can_network_connect
        - httpd_execmem
    - name: Generate SELinux policy
      shell: |
        sepolicy generate --init /usr/sbin/httpd
        echo 'dovecot_read_config(httpd_t)' >> httpd.te
        ./httpd.sh
        ausearch -m AVC -ts recent | audit2allow -R
- name: Create postfixadmin DB
  mysql_db:
    name: postfixadmin
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Set up postfixadmin DB privileges
  mysql_user:
    name: postfixadmin
    password: '{{ postfixadmin_password }}'
    priv: 'postfixadmin.*:ALL,GRANT'
    host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: yes
- name: Render config templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: u=rw,og=r
    owner: root
    group: root
    backup: yes
  loop:
    - { src: "httpd.domain.conf.j2", dest: "/etc/httpd/conf.d/{{ mailserver_hostname }}.conf" }
    - { src: "postfixadmin.config.local.php.j2", dest: "/var/www/postfixadmin/config.local.php" }
    - { src: "httpd.postfixadmin.conf.j2", dest: "/etc/httpd/conf.d/postfixadmin.{{ mailserver_domain }}.conf" }
- name: Enable systemd services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: restarted
  loop:
    - firewalld
    - postfix
    - httpd
    - dovecot
    - mariadb
    - php-fpm
