---
# tasks file for ansible-mailserver
- name: Generate passwords if they don't exist yet
  set_fact:
    postfixadmin_db_password: "{{ postfixadmin_db_password | default(lookup('password', '/tmp/postfixadmin_db_password chars=ascii_letters,digits')) }}"
    horde_db_password: "{{ horde_db_password | default(lookup('password', '/tmp/horde_db_password chars=ascii_letters,digits')) }}"
    mysql_root_password: "{{ mysql_root_password | default(lookup('password', '/tmp/mysql_root_password chars=ascii_letters,digits')) }}"
- name: Fill authorized submit user list
  set_fact:
    authorized_submit_users: "{{ authorized_submit_users + [ item.name ] }}"
  loop: "{{ users }}"
- name: Configure OS
  include: os.yml
- name: Configure DNS caching
  include: dns.yml
- name: Configure MariaDB
  include: mariadb.yml
- name: Configure PostfixAdmin
  include: postfixadmin.yml
- name: Set up Horde
  include: horde.yml
- name: Set up FTP
  include: ftp.yml
- name: Set up ElasticSearch
  include: elasticsearch.yml
- name: Set up SSL
  include: ssl.yml
- name: Configure Apache
  include: httpd.yml
- name: Configure Postfix
  include: postfix.yml
- name: Configure Dovecot
  include: dovecot.yml
- name: Set up DKIM
  include: dkim.yml
- name: Set up DMARC
  include: dmarc.yml
- name: Set up SPAMAssassin
  include: spamassassin.yml
- name: Enable systemd services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: restarted
  loop:
    - firewalld
    - postfix
    - httpd
    - dovecot
    - mariadb
    - php-fpm
    - opendkim
    - opendmarc
    - postgrey
    - named
    - NetworkManager
    - spamassassin
    - spamass-milter
    - vsftpd
    - elasticsearch
