---
# tasks file for ansible-mailserver
- name: Generate passwords if they don't exist yet
  set_fact:
    postfixadmin_db_password: "{{ postfixadmin_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.postfixadmin_db_password chars=ascii_letters,digits')) }}"
    horde_db_password: "{{ horde_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.horde_db_password chars=ascii_letters,digits')) }}"
    powerdns_db_password: "{{ powerdns_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.powerdns_db_password chars=ascii_letters,digits')) }}"
    powerdns_api_key: "{{ powerdns_api_key | default(lookup('password', '/tmp/ansible-mailserver-install.powerdns_api_key chars=ascii_letters,digits')) }}"
    mysql_root_password: "{{ mysql_root_password | default(lookup('password', '/tmp/ansible-mailserver-install.mysql_root_password chars=ascii_letters,digits')) }}"
    ldap_admin_password: "{{ ldap_admin_password | default(lookup('password', '/tmp/ansible-mailserver-install.ldap_admin_password chars=ascii_letters,digits')) }}"
    mariabackup_password: "{{ mariabackup_password | default(lookup('password', '/tmp/ansible-mailserver-install.mariabackup_password chars=ascii_letters,digits')) }}"
    horde_secret_key: "{{ horde_secret_key | default(lookup('password', '/tmp/ansible-mailserver-install.horde_secret_key chars=ascii_letters,digits')) }}"
  no_log: yes
- name: Fill authorized submit user list
  set_fact:
    authorized_submit_users: "{{ authorized_submit_users + [ item.name ] }}"
  loop: "{{ users }}"
  no_log: yes
- name: Configure OS
  import_tasks: os.yml
- name: Configure MariaDB
  import_tasks: mariadb.yml
- name: Configure DNS
  import_tasks: dns.yml
- name: Configure PostfixAdmin
  import_tasks: postfixadmin.yml
- name: Set up SSL
  import_tasks: ssl.yml
- name: Configure LDAP
  import_tasks: ldap.yml
- name: Set up Horde
  import_tasks: horde.yml
- name: Set up ElasticSearch
  import_tasks: elasticsearch.yml
- name: Set up FTP
  import_tasks: ftp.yml
- name: Configure Apache
  import_tasks: httpd.yml
- name: Set up SPAMAssassin
  import_tasks: spamassassin.yml
- name: Configure Antivirus
  import_tasks: antivirus.yml
- name: Configure Redis
  import_tasks: redis.yml
- name: Configure Postfix
  import_tasks: postfix.yml
- name: Configure Dovecot
  import_tasks: dovecot.yml
- name: Sync old IMAP account
  import_tasks: offlineimap.yml
  when: "{{ item.old_imap_mail is defined }}"
  loop: "{{ users }}"
  become: yes
  become_user: "{{ item.name }}"
- name: Set up DKIM
  import_tasks: dkim.yml
- name: Set up DMARC
  import_tasks: dmarc.yml
- name: Set up MongoDB
  import_tasks: mongodb.yml
- name: Set up WebDav
  import_tasks: webdav.yml
- name: Set up WireGuard
  import_tasks: wireguard.yml
- name: Set up backups
  import_tasks: backups.yml
- name: Configure fail2ban
  import_tasks: fail2ban.yml
