---
# tasks file for ansible-mailserver
- name: Gather facts
  ansible.builtin.setup:
- name: Generate passwords if they don't exist yet
  ansible.builtin.set_fact:
    # postfixadmin_db_password: "{{ postfixadmin_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.postfixadmin_db_password chars=ascii_letters,digits')) }}"
    powerdns_db_password: "{{ powerdns_db_password | default(lookup('password', '/tmp/ansible-mailserver-install.powerdns_db_password chars=ascii_letters,digits')) }}"
    powerdns_api_key: "{{ powerdns_api_key | default(lookup('password', '/tmp/ansible-mailserver-install.powerdns_api_key chars=ascii_letters,digits')) }}"
    mysql_root_password: "{{ mysql_root_password | default(lookup('password', '/tmp/ansible-mailserver-install.mysql_root_password chars=ascii_letters,digits')) }}"
    ldap_admin_password: "{{ users | selectattr('name', 'equalto', mailserver_admin_user) | map(attribute='password') | first }}"
    mariabackup_password: "{{ mariabackup_password | default(lookup('password', '/tmp/ansible-mailserver-install.mariabackup_password chars=ascii_letters,digits')) }}"
  no_log: yes
  tags: always
- name: Configure OS
  ansible.builtin.import_tasks: os/main.yml
  tags: os
- name: Configure MariaDB
  ansible.builtin.import_tasks: mariadb/main.yml
  tags: mariadb
- name: Configure DNS
  ansible.builtin.import_tasks:  dns/main.yml
  tags:
    - dns
    - poweradmin
    - dyndns
# - name: Configure PostfixAdmin
#   ansible.builtin.import_tasks: mail/postfixadmin.yml
#   tags:
#     - postfix
#     - postfixadmin
- name: Set up SSL
  ansible.builtin.import_tasks: security/ssl.yml
  tags:
    - ssl
    - security
- name: Set up Kolab
  ansible.builtin.import_tasks: kolab/main.yml
  tags:
    - kolab
    - users
    - mail
# - name: Add users
#   ansible.builtin.import_tasks: os/users.yml
#   tags: users
- name: Set up ElasticSearch
  ansible.builtin.import_tasks: misc/elasticsearch.yml
  tags: elasticsearch
- name: Set up FTP
  ansible.builtin.import_tasks: misc/ftp.yml
  tags: ftp
- name: Configure Apache
  ansible.builtin.import_tasks: httpd/main.yml
  tags:
    - httpd
    - dyndns
    - kolab
    # - postfixadmin
    - poweradmin
    - wireguard
    - webdav
- name: Set up SPAMAssassin
  ansible.builtin.import_tasks: mail/spamassassin.yml
  tags:
    - spamassassin
    - mail
- name: Configure Antivirus
  ansible.builtin.import_tasks: security/antivirus.yml
  tags:
    - antivirus
    - security
- name: Configure Redis
  ansible.builtin.import_tasks: misc/redis.yml
  tags: redis
- name: Configure Postfix
  ansible.builtin.import_tasks: mail/postfix.yml
  tags:
    - postfix
    - mail
- name: Sync old IMAP account
  # noqa jinja[invalid] for some reason this was the only way I found to pass the variable to the included task list
  ansible.builtin.include_tasks: mail/imapsync.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: current_user
  vars:
    current_user: "{{ current_user }}"
  no_log: yes
  tags:
    - imapsync
    - users
    - mail
- name: Set up DKIM
  ansible.builtin.import_tasks: mail/dkim.yml
  tags:
    - dkim
    - mail
- name: Set up DMARC
  ansible.builtin.import_tasks: mail/dmarc.yml
  tags:
    - dmarc
    - mail
- name: Set up MongoDB
  ansible.builtin.import_tasks: misc/mongodb.yml
  tags: mongodb
- name: Set up WebDav
  ansible.builtin.import_tasks: httpd/webdav.yml
  tags: webdav
- name: Set up WireGuard
  ansible.builtin.import_tasks: wireguard/main.yml
  tags:
    - wireguard
    - dyndns
    - poweradmin
    # - postfixadmin
- name: Set up backups
  ansible.builtin.import_tasks: backups/main.yml
  tags: backup
- name: Configure fail2ban
  ansible.builtin.import_tasks: security/fail2ban.yml
  tags:
    - fail2ban
    - security
