- name: Check SELinux status
  shell: getenforce
  register: getenforce
- name: "Set hostname to {{ mailserver_hostname}}"
  command: "hostnamectl set-hostname {{ mailserver_hostname }}"
- name: Install requiremets
  block:
    - name: Install packages
      include: packages.yml
  rescue:
    - name: Find repo configs
      find:
        paths: /etc/yum.repos.d
        patterns: "*.repo"
      register: repo_files
    - name: Disable CentOS mirrorlist
      replace:
        path: "{{ item }}"
        regexp: "mirrorlist=http://mirrorlist.centos.org"
        replace: "#mirrorlist=http://mirrorlist.centos.org"
        validate: "grep '#mirrorlist=http://mirrorlist.centos.org' %s"
      loop: "{{ repo_files.files }}"
    - name: Move to CentOS Vault
      replace:
        path: "{{ item }}"
        regexp: "#baseurl=http://mirror.centos.org"
        replace: "baseurl=http://vault.centos.org"
        validate: "grep '^baseurl=http://vault.centos.org' %s"
      loop: "{{ repo_files.files }}"
    - name: Install packages
      include: packages.yml
- name: Set up OS mail aliases
  lineinfile:
    path: /etc/aliases
    regexp: '^root: *{{ mailserver_admin_user }}'
    line: 'root: {{ mailserver_admin_user }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
- name: Create OS users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512')| default(lookup('password', '/tmp/ansible-mailserver-install.' + item.name + '_password chars=ascii_letters,digits,punctuation')) }}"
    state: present
  loop: "{{ users }}"
  no_log: yes
- name: Set up cron mailto
  cron:
    backup: yes
    env: yes
    name: MAILTO
    job: "{{ mailserver_admin_user }}@{{ mailserver_domain }}"
