---
- name: Check SELinux status
  shell: getenforce
  register: getenforce
  tags: always
- name: "Set hostname to {{ mailserver_hostname }}.{{ mailserver_domain }}" # noqa name[template] we need to be informative, even if we deviate from the standards
  ansible.builtin.command: "hostnamectl set-hostname {{ mailserver_hostname }}.{{ mailserver_domain }}"
- name: Enable IPv6
  when: ansible_default_ipv6.address is not defined
  block:
    - name: Enable IPv6 via sysctl
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 0
        state: present
        sysctl_set: true
      loop:
        - "net.ipv6.conf.all.disable_ipv6"
        - "net.ipv6.conf.{{ ansible_default_ipv4.interface }}.disable_ipv6"
      register: ipv6_enable
    - name: Reboot to pick up changes
      when: ipv6_enable.changed
      reboot:
        reboot_timeout: 600
        msg: "Reboot initiated by Ansible to enable IPv6"
    - name: Gather facts
      setup:
- name: Install requiremets
  block:
    - name: Install packages
      import_tasks: packages.yml
  rescue:
    - name: Find repo configs
      find:
        paths: /etc/yum.repos.d
        patterns: "*.repo"
      register: repo_files
    - name: Disable CentOS mirrorlist
      replace:
        path: "{{ item.path }}"
        regexp: "^mirrorlist=http://mirrorlist.centos.org"
        replace: "#mirrorlist=http://mirrorlist.centos.org"
        validate: "grep '#mirrorlist=http://mirrorlist.centos.org' %s"
      loop: "{{ repo_files.files }}"
    - name: Move to CentOS Vault
      replace:
        path: "{{ item.path }}"
        regexp: "#baseurl=http://mirror.centos.org"
        replace: "baseurl=http://vault.centos.org"
        validate: "grep '^baseurl=http://vault.centos.org' %s"
      loop: "{{ repo_files.files }}"
    - name: Install packages
      import_tasks: packages.yml
- name: Set up OS mail aliases
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: '^root: *{{ mailserver_admin_user }}'
    line: 'root: {{ mailserver_admin_user }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
- name: Create OS users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512')| default(lookup('password', '/tmp/ansible-mailserver-install.' + item.name + '_password chars=ascii_letters,digits,punctuation')) }}"
    groups: "{{ 'wheel' if item.name == mailserver_admin_user }}"
    append: yes
    state: present
  loop: "{{ users }}"
  register: user_info
  no_log: yes
  notify: Warn on passwords
  tags:
    - all
    - ftp
    - httpd
    - poweradmin
    - wireguard
    - dns
    - horde
    - ldap
    - postfixadmin
- name: Enable ip_conntrack
  community.general.modprobe:
    name: ip_conntrack
    state: present
  tags: wireguard
- name: Set up cron mailto
  cron:
    backup: yes
    env: yes
    name: MAILTO
    job: "hostmaster+cron@{{ mailserver_domain }}"
- name: Add GO path to PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/gopath.sh
    line: 'export PATH=$PATH:$(go env GOPATH)/bin'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    create: yes
    backup: yes
  tags: ssl
