- name: Check SELinux status
  shell: getenforce
  register: getenforce
- name: Set hostname
  command: "hostnamectl set-hostname {{ mailserver_hostname }}"
- name: Install packages
  include: packages.yml
- name: Set up mail aliases
  lineinfile:
    path: /etc/aliases
    regexp: '^root: *{{ mailserver_admin_user }}'
    line: 'root: {{ mailserver_admin_user }}'
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
- name: Create OS users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512')| default(lookup('password', '/tmp/' + item.name + '_password chars=ascii_letters,digits,punctuation')) }}"
    state: present
  loop: "{{ users }}"
  no_log: yes
- name: Add vmail group
  group:
    name: vmail
    system: yes
    gid: 2000
- name: Add vmail user
  user:
    name: vmail
    group: vmail
    create_home: no
    system: yes
    uid: 2000
- name: Create policyd-spf group
  group:
    name: policyd-spf
    state: present
- name: Create policyd-spf user
  user:
    name: policyd-spf
    group: policyd-spf
    create_home: no
    shell: /bin/false
- name: Apply mail aliases
  command: newaliases
- name: Set up cron mailto
  cron:
    backup: yes
    env: yes
    name: MAILTO
    job: "{{ mailserver_admin_user }}@{{ mailserver_domain }}"
- name: Configure local DNS cache
  nmcli:
    conn_name: ens192
    dns4:
      - 127.0.0.1
      - 8.8.8.8
      - 1.1.1.1
    state: present
    type: ethernet
- name: Make sure BIND and NetworkManager are running
  systemd:
    name: named
    daemon_reload: yes
    enabled: yes
    state: restarted
- name: Reload DNS cache
  command: rndc reload
- name: Create resolved.conf.d directory
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: u=rwX,og=rX
- name: Enable local DNS caching
  blockinfile:
    path: /etc/systemd/resolved.conf.d/LocalDNSCache.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK Local DNS cache"
    block: |
      [Resolve]
      Cache=yes
      # CacheFromLocalhost=yes
      Domains={% for custom_domain in [mailserver_domain] + custom_domains %}{{ custom_domain }} {% if loop.index != loop.length %} {% endif %}{% endfor %}
      DNS=127.0.0.1 8.8.8.8 1.1.1.1
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
- name: Make sure resolved is running
  systemd:
    name: systemd-resolved
    daemon_reload: yes
    enabled: yes
    state: restarted
