- name: Set up ELRepo
  dnf:
    name: https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    disable_gpg_check: yes
- name: Set up Remi repository
  dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    disable_gpg_check: yes
- name: Reset the PHP DNF module
  command: dnf module reset php -y
- name: Enable the Remi PHP DNF module
  command: dnf module enable php:remi-7.4 -y
- name: Install packages
  package:
    name:
      - postfix
      - mailx
      - epel-release
      - certbot
      - httpd
      - python3-certbot-apache
      - dovecot
      - mariadb-server
      - mariadb
      - python3-mysqlclient
      - wget
      - tar
      - php-fpm
      - php-imap
      - php-mbstring
      - php-mysqlnd
      - php-gd
      - php-opcache
      - php-json
      - php-curl
      - php-zip
      - php-xml
      - php-bz2
      - php-intl
      - php-gmp
      - binutils
      - rpm-build
      - setools-console
      - policycoreutils-python3
      - policycoreutils-devel
      - php-cli
      - postfix-mysql
      - dovecot-mysql
      - pypolicyd-spf
      - opendkim
      - perl-Getopt-Long
      - opendmarc
      - bind-utils
      - postgrey
      - postfix-perl-scripts
      - mutt
      - bind
      - NetworkManager-libnm
      - nm-connection-editor
      - spamassassin
      - spamass-milter
      - dovecot-pigeonhole
      - php-devel
      - php74-php-devel
      - php-pear
      - php56-php-channel-horde
      # - php-horde-horde-lz4
      - php56-php-horde-horde-lz4
      - ImageMagick
      - php-pecl-imagick
      - php56-php-pecl-imagick
      - aspell
      - memcached
      - php56-php-pecl-memcache
      - php-pecl-memcache
      - php-pecl-http
      - mod_ssl
      - php-bcmath
      - php56-php-bcmath
      - php-ldap
      - php56-php-ldap
      - libmemcached
      - gettext
      - gettext-common-devel
      - gettext-devel
      - gettext-libs
      - php-xml
      - php56-php-xml
      - php56-php-pecl-dom-varimport
      - php56-php-pecl-dom-varimport-devel
      - php-mysqlnd
      - php-pecl-mysql
      - php-pecl-mysql-xdevapi
      - php56-php-mysqlnd
      - openldap
      - openldap-clients
      - openldap-devel
      - php-ldap
      - php56-php-ldap
      - phpldapadmin
      - php-kolabformat
      - php-mbstring
      - php56-php-mbstring
      - gd
      - gd-devel
      - php-gd
      - php56-php-gd
      - tidy
      - libtidy
      - libtidy-devel
      - php-tidy
      - php56-php-tidy
      - php-pecl-crypto
      - php56-php-pecl-crypto
      - intltool
      - php-intl
      - php56-php-intl
      - curl
      - libcurl
      - libcurl-devel
      - proftpd
      - java-1.8.0-openjdk
    state: latest
- name: Install ElasticSearch
  dnf:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.0.1-x86_64.rpm
    disable_gpg_check: yes
