---
- name: Install EL repositories
  tags:
    - always
  ansible.builtin.package:
    name:
      - yum-utils
      - epel-release
      - elrepo-release
    state: latest # noqa package-latest I do prefer fresh stuff ;)
- name: Set up UEK repository
  tags: wireguard
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/uek-ol8.repo
    marker: "# {mark} ANSIBLE MANAGED BLOCK Unbreakable Enterprise Kernel Release 7 for Oracle Linux repository"
    block: |
      [ol8_UEKR7]
      name=Latest Unbreakable Enterprise Kernel Release 7 for Oracle Linux $releasever ($basearch)
      baseurl=https://yum.oracle.com/repo/OracleLinux/OL$releasever/UEKR7/$basearch/
      gpgkey=https://yum.oracle.com/RPM-GPG-KEY-oracle-ol$releasever
      gpgcheck=1
      enabled=1

      [ol8_baseos_latest]
      name=Oracle Linux 8 BaseOS Latest ($basearch)
      baseurl=https://yum.oracle.com/repo/OracleLinux/OL$releasever/baseos/latest/$basearch/
      gpgkey=https://yum.oracle.com/RPM-GPG-KEY-oracle-ol$releasever
      gpgcheck=1
      enabled=0
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
- name: Set up Remi repository
  tags: horde
  ansible.builtin.dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    disable_gpg_check: yes
# - name: Enable RPM Fusion
#   tags: horde
#   ansible.builtin.dnf:
#     name:
#       - "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
#       - "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
#     disable_gpg_check: yes
# - name: Set up Cheese repository
#   tags: horde
#   ansible.builtin.dnf:
#     name: "http://www.nosuchhost.net/~cheese/fedora/packages/epel-{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/cheese-release-8-1.el8.noarch.rpm"
#     disable_gpg_check: yes
- name: Set up ElasticSearch repository
  tags: elasticsearch
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/elastic.repo
    marker: "# {mark} ANSIBLE MANAGED BLOCK ElasticSearch 8.x repository"
    block: |
      [elasticsearch]
      name=Elasticsearch repository for 8.x packages
      baseurl=https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
- name: Accept Kolab GPG key
  tags: kolab
  ansible.builtin.rpm_key:
    state: present
    key: https://mirror.apheleia-it.ch/repos/Kolab:/16/key.asc
- name: Set up Kolab repository
  tags: kolab
  ansible.builtin.dnf:
    name: "https://mirror.apheleia-it.ch/repos/Kolab:/16/kolab-16-for-el{{ ansible_distribution_major_version }}.rpm"
# - name: Set up Symas OpenLDAP for Linux RPM repository
#   tags:
#     - ldap
#     - users
#   ansible.builtin.blockinfile:
#     path: /etc/yum.repos.d/sofl.repo
#     marker: "# {mark} ANSIBLE MANAGED BLOCK Symas OpenLDAP for Linux RPM repository"
#     block: |
#       [sofl]
#       name=Symas OpenLDAP for Linux RPM repository
#       baseurl=https://repo.symas.com/repo/rpm/SOFL/rhel{{ ansible_distribution_major_version }}
#       gpgkey=https://repo.symas.com/repo/gpg/RPM-GPG-KEY-symas-com-signing-key
#       gpgcheck=1
#       enabled=1
#     mode: u=rw,og=r
#     owner: root
#     group: root
#     state: present
#     backup: yes
#     create: yes
- name: Set up Extra Packages for Enterprise Linux 7 repository
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/epel-el7.repo
    marker: "# {mark} ANSIBLE MANAGED BLOCK Extra Packages for Enterprise Linux 7 repository"
    block: |
      [epel-el7]
      name=Extra Packages for Enterprise Linux 7 - x86_64
      baseurl=https://dl.fedoraproject.org/pub/epel/7/x86_64/
      enabled=0
      gpgcheck=0
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
- name: Set up PowerDNS repository
  tags: dns
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/powerdns.repo
    marker: "# {mark} ANSIBLE MANAGED BLOCK PowerDNS repository"
    block: |
      [powerdns-auth-master]
      name=PowerDNS repository for PowerDNS Authoritative Server – master branch
      baseurl=http://repo.powerdns.com/el/$basearch/$releasever/auth-master
      gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
      gpgcheck=1
      enabled=1
      priority=90
      includepkg=pdns*

      [powerdns-auth-master-debuginfo]
      name=PowerDNS repository for PowerDNS Authoritative Server – master branch debug symbols
      baseurl=http://repo.powerdns.com/el/$basearch/$releasever/auth-master/debug
      gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
      gpgcheck=1
      enabled=0
      priority=90
      includepkg=pdns*

      [powerdns-recursor-master]
      name=PowerDNS repository for PowerDNS recursor – master branch
      baseurl=http://repo.powerdns.com/el/$basearch/$releasever/rec-master
      gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
      gpgcheck=1
      enabled=1
      priority=90
      includepkg=pdns*

      [powerdns-recursor-master-debuginfo]
      name=PowerDNS repository for PowerDNS recursor – master branch debug symbols
      baseurl=http://repo.powerdns.com/el/$basearch/$releasever/rec-master/debug
      gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
      gpgcheck=1
      enabled=0
      priority=90
      includepkg=pdns*

      [dnsdist-auth-master]
      name=PowerDNS repository for DNSDist – master branch
      baseurl=http://repo.powerdns.com/el/$basearch/$releasever/dnsdist-master
      gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
      gpgcheck=1
      enabled=1
      priority=90
      includepkg=dnsdist*

      [dnsdist-auth-master-debuginfo]
      name=PowerDNS repository for DNSDist – master branch debug symbols
      baseurl=http://repo.powerdns.com/el/$basearch/$releasever/dnsdist-master/debug
      gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
      gpgcheck=1
      enabled=0
      priority=90
      includepkg=dnsdist*

    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
- name: Set up MongoDB repository
  tags: mongodb
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/mongodb-org-5.0.repo
    marker: "# {mark} ANSIBLE MANAGED BLOCK MongoDB 5.0 repository"
    block: |
      [mongodb-org-5.0]
      name=MongoDB 5.0 Repository
      baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/5.0/$basearch/
      gpgcheck=0
      enabled=1
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
- name: Enable PowerTools
  ansible.builtin.command: dnf config-manager --set-enable powertools
  register: enable_powertools
  changed_when: enable_powertools.rc == 0
- name: Enable the go-toolset DNF module
  ansible.builtin.command: dnf module enable go-toolset -y
  register: enable_go_toolset
  changed_when: enable_go_toolset.rc == 0
- name: Query DNF repo list
  tags:
    - ldap
    - dns
  ansible.builtin.command: dnf repolist
  register: dnf_repolist
  changed_when: dnf_repolist.rc == 0
- name: Enable the COPR repositories
  when: "{{ ('copr:copr.fedorainfracloud.org:' ~ (item | split(' ') | first | replace('@', 'group_') | replace('/', ':'))) not in dnf_repolist.stdout }}" # noqa no-jinja-when this logic starts with a varable concatenation, no other way I found to do such
  ansible.builtin.command: "dnf copr enable -y {{ item }}"
  tags:
    - ldap
    - dns
  loop:
    - "@389ds/389-directory-server"
    - "eclipseo/golang-ng custom-1-x86_64"
  register: enable_copr_repo
  changed_when: enable_copr_repo.rc == 0
- name: Enable the php:remi-7.4 DNF module
  tags:
    # - horde
    - always
  ansible.builtin.command: dnf module enable php:remi-7.4 -y
  register: enable_php74_module
  changed_when: enable_php74_module.rc == 0
- name: Install packages
  tags:
    - always
  ansible.builtin.package:
    name:
      - postfix
      - mailx
      - certbot
      - httpd
      - python3-certbot-apache
      # - dovecot
      - mariadb-server
      - mariadb
      - python3-mysqlclient
      - wget
      - tar
      - binutils
      - rpm-build
      - setools-console
      - policycoreutils-python3
      - policycoreutils-devel
      - postfix-mysql
      # - dovecot-mysql
      - pypolicyd-spf
      - opendkim
      - opendkim-tools
      - perl-Getopt-Long
      - opendmarc
      - bind-utils
      - postgrey
      - postfix-perl-scripts
      - NetworkManager-libnm
      - nm-connection-editor
      - spamassassin
      - spamass-milter
      # - dovecot-pigeonhole
      - ImageMagick
      - aspell
      - memcached
      - mod_ssl
      - php-bcmath
      - libmemcached
      - gettext
      - gettext-common-devel
      - gettext-devel
      - gettext-libs
      - openldap
      - openldap-clients
      - openldap-devel
      - gd
      - gd-devel
      - tidy
      - libtidy
      - libtidy-devel
      - intltool
      - curl
      - libcurl
      - libcurl-devel
      - vsftpd
      - java-1.8.0-openjdk
      - elasticsearch
      - python3-dns
      - python3-py3dns
      - mariadb-backup
      - cyrus-sasl-devel
      - libtool-ltdl-devel
      - openssl-devel
      - libdb-devel
      - make
      - libtool
      - autoconf
      - gcc
      - perl
      - perl-devel
      - GeoIP-devel
      - GeoIP
      - GeoIP-GeoLite-data
      - GeoIP-GeoLite-data-extra
      - libgweather
      - libgweather-devel
      - cyrus-sasl-ldap
      - mod_ldap
      - openssh-ldap
      - openssh-ldap-authkeys
      - postfix-ldap
      - sssd-ldap
      # - 389-ds-base
      - fortune-mod
      - mongodb-org
      - fail2ban-all
      - fail2ban-firewalld
      - fail2ban-selinux
      - fail2ban-sendmail
      - fail2ban-server
      - fail2ban-systemd
      - fail2ban
      - procmail
      - fetchmail
      - mutt
      - moreutils
      - incron
      - perl-DBI
      - perl-MIME-Base64
      - perl-File-Temp
      - perl-Sys-Syslog
      - perl-LockFile-Simple
      - figlet
      - telnet
      - htop
      - iotop
      - screen
      - amavisd-milter
      - clamav-unofficial-sigs
      - clamav-milter
      - clamav-update
      - iptables-services
      - conntrack-tools
      - pdns
      - pdns-backend-mysql
      - pdns-recursor
      - libedit-devel
      - boost-devel
      - lua-devel
      - libsodium-devel
      - systemd-devel
      - ragel
      - dnsdist
      - python3-netaddr
      - redis
      - mod_authnz_pam
      - mod_authnz_external
      - pwauth
      - wireguard-tools
      - bindfs
      - golang
      - python3-pyyaml
      - python3-jinja2
      - qrencode
      - python3-pip
      - golang-github-acme-lego
      - perl-Proc-ProcessTable
      - perl-CGI
      - imapsync
      - aide
      - kolab
      - php74-php-pecl-memcache
      # - sssd
      # - oddjob-mkhomedir
      # - libsss_sudo
      # - symas-openldap-clients
      # - symas-openldap-servers
      - nss-pam-ldapd
      # - php56-php-bcmath
      # - php56-php-channel-horde
      # - php56-php-horde-horde-lz4
      # - php56-php-xml
      # - php56-php-pecl-dom-varimport
      # - php56-php-mysqlnd
      # - php56-php-ldap
      # - php56-php-mbstring
      # - php56-php-gd
      # - php56-php-tidy
      # - php56-php-pecl-crypto
      # - php56-php-intl
      # - php56-php-pecl-geoip
      # - php56-php-pecl-imagick
      # - php56-php-pecl-memcache
      # - php-gettext-gettext
    state: latest # noqa package-latest I do prefer fresh stuff ;)
# - name: Reset the PHP DNF module
#   ansible.builtin.command: dnf module reset php -y
#   tags:
#     - wireguard
#     - dyndns
# - name: Enable the php:remi-8.1 DNF module
#   tags:
#     - wireguard
#     - dyndns
#   ansible.builtin.command: dnf module enable php:remi-8.1 -y
# - name: Install PHP 8.1 packages
#   tags:
#     - wireguard
#     - dyndns
#   ansible.builtin.package:
#     name:
#       - php81-php-fpm
#       - php81-php-intl
#       - php81-php-pecl-crypto
#       - php81-php-pdo
#       - php81-php-mysql
#       - php81-php-mysqlnd
#       - php81-php-pecl-mysql-xdevapi
#       - php81-php-ldap
#     state: latest # noqa package-latest I do prefer fresh stuff ;)
#   register: php81_packages
# - name: Restart php81-php-fpm
#   when: php81_packages.changed
#   tags:
#     - wireguard
#     - dyndns
#   ansible.builtin.systemd_service:
#     name: php81-php-fpm
#     daemon_reload: yes
#     enabled: yes
#     state: restarted
- name: Reset the PHP DNF module
  ansible.builtin.command: dnf module reset php -y
  tags:
    - always
  register: reset_php_module
  changed_when: reset_php_module.rc == 0
# - name: Enable the php:remi-7.4 DNF module
#   tags: horde
#   ansible.builtin.command: dnf module enable php:remi-7.4 -y
#   register: enable_php74_module
#   changed_when: enable_php74_module.rc == 0
# - name: Install PHP 7.4 packages
#   tags: horde
#   ansible.builtin.dnf:
#     name:
#       - phpldapadmin
#       - phpunit7
#       - php74-php-fpm
#       - php74-php-pear
#       - php74-php-tidy
#       - php74-php
#       - php74-php-ldap
#       - php74-php-mysql
#       - php74-php-odbc
#       - php74-php-mcrypt
#       - php74-php-mhash
#       - php74-php-pecl-mysql
#       - php74-php-pecl-mysql-xdevapi
#       - php74-php-pecl-crypto
#       - php74-php-pecl-geoip
#       - php74-php-pecl-pam
#       - php74-php-pecl-imagick
#       - php74-php-pecl-memcache
#       - php74-php-pecl-http
#       - php74-php-devel
#       - php74-php-imap
#       - php74-php-mbstring
#       - php74-php-mysqlnd
#       - php74-php-gd
#       - php74-php-opcache
#       - php74-php-json
#       - php74-php-curl
#       - php74-php-zip
#       - php74-php-xml
#       - php74-php-bz2
#       - php74-php-intl
#       - php74-php-gmp
#       - php74-php-cli
#       - php-channel-horde
#       - php-horde-Horde-Alarm
#       - php-horde-Horde-Argv
#       - php-horde-Horde-Auth
#       - php-horde-Horde-Autoloader
#       - php-horde-Horde-Browser
#       - php-horde-Horde-Cache
#       - php-horde-Horde-Cli
#       - php-horde-Horde-Compress
#       - php-horde-Horde-Core
#       - php-horde-Horde-Crypt
#       - php-horde-Horde-Dav
#       - php-horde-Horde-Db
#       - php-horde-Horde-Editor
#       - php-horde-Horde-ElasticSearch
#       - php-horde-Horde-Http
#       - php-horde-Horde-Image
#       - php-horde-Horde-Imap-Client
#       - php-horde-Horde-Ldap
#       - php-horde-Horde-ListHeaders
#       - php-horde-Horde-Log
#       - php-horde-Horde-Mail
#       - php-horde-Horde-Mail-Autoconfig
#       - php-horde-Horde-Memcache
#       - php-horde-Horde-Mime
#       - php-horde-Horde-Mime-Viewer
#       - php-horde-Horde-Notification
#       - php-horde-Horde-Oauth
#       - php-horde-Horde-Pdf
#       - php-horde-Horde-Perms
#       - php-horde-Horde-Prefs
#       - php-horde-Horde-Role
#       - php-horde-Horde-Routes
#       - php-horde-Horde-Rpc
#       - php-horde-Horde-Service-Weather
#       - php-horde-Horde-Smtp
#       - php-horde-Horde-Socket-Client
#       - php-horde-Horde-SyncMl
#       - php-horde-Horde-Template
#       - php-horde-Horde-Test
#       - php-horde-Horde-Text-Filter
#       - php-horde-Horde-Text-Filter-Csstidy
#       - php-horde-Horde-Text-Flowed
#       - php-horde-Horde-Tree
#       - php-horde-Horde-Url
#       - php-horde-Horde-Util
#       - php-horde-Horde-View
#       - php-horde-Horde-Xml-Element
#       - php-horde-horde
#       - php-horde-passwd
#       - php-horde-Horde-Compress-Fast
#       - php-horde-Horde-Crypt-Blowfish
#       - php-horde-Horde-Icalendar
#       - php-horde-Horde-Itip
#       - php-horde-Horde-Mapi
#       - php-horde-Horde-OpenXchange
#       - php-horde-Horde-Secret
#       - php-horde-Horde-Service-Gravatar
#       - php-horde-Horde-Text-Diff
#       - php-horde-Horde-Timezone
#       - php-horde-Horde-Vfs
#       - php-horde-imp
#       - php-horde-kronolith
#       - php-horde-turba
#       - php-horde-Horde-Mongo
#       - php-horde-ingo
#       - php-horde-mnemo
#       - php-horde-wicked
#       - php-pear-Text-Figlet
#     enablerepo: remi
#     # enablerepo: cheese
#     state: latest # noqa package-latest I do prefer fresh stuff ;)
#   register: php74_packages
# - name: Restart php74-php-fpm
#   # noqa no-handler we want results now, no time to wait for a handler
#   when: php74_packages.changed
#   tags: horde
#   ansible.builtin.systemd_service:
#     name: php74-php-fpm
#     daemon_reload: yes
#     enabled: yes
#     state: restarted
- name: Install EL7 packages
  ansible.builtin.dnf:
    name:
      - wiredtiger
      - wiredtiger-devel
      - getmail
    enablerepo: epel-el7
    state: latest # noqa package-latest I do prefer fresh stuff ;)
- name: Enable WireGuard kernel module
  tags: wireguard
  block:
    - name: Load the WireGuard kernel module
      community.general.modprobe:
        name: wireguard
  rescue:
    - name: Install UEK packages
      ansible.builtin.dnf:
        name:
          - kmod-wireguard
        enablerepo: ol8_baseos_latest
        state: latest # noqa package-latest I do prefer fresh stuff ;)
    - name: Reboot to pick up changes
      ansible.builtin.reboot:
        reboot_timeout: 600
        msg: "Reboot initiated by Ansible to enable WireGuard"
    - name: Load the WireGuard kernel module
      community.general.modprobe:
        name: wireguard
# - name: Install PEAR packages
#   tags: horde
#   community.general.pear:
#     name: pear.horde.org/Horde_ActiveSync
#     state: latest # noqa package-latest I do prefer fresh stuff ;)
# - name: Install go packages
#   ansible.builtin.command: "go install {{ item }}"
#   loop:
#     - github.com/go-acme/lego/v4/cmd/lego@latest
#   tags: ssl
# - name: Copy GO binaries to /usr/local/bin
#   ansible.builtin.copy:
#     src: "{{ ansible_env.HOME }}/go/bin/"
#     dest: /usr/local/bin/
#     remote_src: yes
#     backup: yes
- name: Download as-is executables
  tags: imapsync
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: u=rwx,go=rx
    force: yes
    backup: yes
  loop:
    - { url: "https://github.com/quentinsf/IMAPdedup/raw/master/imapdedup.py", dest: "/usr/local/bin/imapdedup.py" }
- name: Reset the PHP DNF module
  ansible.builtin.command: dnf module reset php -y
  tags:
    - always
  register: reset_php_module
  changed_when: reset_php_module.rc == 0
