- name: Set up Remi repository
  dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.rpm"
    disable_gpg_check: yes
- name: Set up ElasticSearch repository
  blockinfile:
    path: /etc/yum.repos.d/elastic.repo
    marker: "# {mark} ANSIBLE MANAGED BLOCK ElasticSearch 8.x repository"
    block: |
      [elasticsearch]
      name=Elasticsearch repository for 8.x packages
      baseurl=https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
    create: yes
# - name: Set up MongoDB repository
#   blockinfile:
#     path: /etc/yum.repos.d/mongodb-org-5.0.repo
#     marker: "# {mark} ANSIBLE MANAGED BLOCK MongoDB 5.0 repository"
#     block: |
#       [mongodb-org-5.0]
#       name=MongoDB 5.0 Repository
#       baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/5.0/$basearch/
#       gpgcheck=0
#       enabled=1
#     mode: u=rw,og=r
#     owner: root
#     group: root
#     state: present
#     backup: yes
#     create: yes
- name: Enable PowerTools
  command: dnf config-manager --set-enable powertools
- name: Reset the PHP DNF module
  command: dnf module reset php -y
- name: Enable DNF modules
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - '@php:remi-7.4'
    - '@389-directory-server:stable/default'
- name: Install packages
  package:
    name:
      - postfix
      - mailx
      - epel-release
      - elrepo-release
      - certbot
      - httpd
      - python3-certbot-apache
      - dovecot
      - mariadb-server
      - mariadb
      - python3-mysqlclient
      - wget
      - tar
      - php-fpm
      - php-imap
      - php-mbstring
      - php-mysqlnd
      - php-gd
      - php-opcache
      - php-json
      - php-curl
      - php-zip
      - php-xml
      - php-bz2
      - php-intl
      - php-gmp
      - binutils
      - rpm-build
      - setools-console
      - policycoreutils-python3
      - policycoreutils-devel
      - php-cli
      - postfix-mysql
      - dovecot-mysql
      - pypolicyd-spf
      - opendkim
      - perl-Getopt-Long
      - opendmarc
      - bind-utils
      - postgrey
      - postfix-perl-scripts
      - mutt
      - bind
      - NetworkManager-libnm
      - nm-connection-editor
      - spamassassin
      - spamass-milter
      - dovecot-pigeonhole
      - php-devel
      - php74-php-devel
      - php-pear
      - php56-php-channel-horde
      - php56-php-horde-horde-lz4
      - ImageMagick
      - php-pecl-imagick
      - php56-php-pecl-imagick
      - aspell
      - memcached
      - php56-php-pecl-memcache
      - php-pecl-memcache
      - php-pecl-http
      - mod_ssl
      - php-bcmath
      - php56-php-bcmath
      - php-ldap
      - php56-php-ldap
      - libmemcached
      - gettext
      - gettext-common-devel
      - gettext-devel
      - gettext-libs
      - php-xml
      - php56-php-xml
      - php56-php-pecl-dom-varimport
      - php-mysqlnd
      - php-pecl-mysql
      - php-pecl-mysql-xdevapi
      - php56-php-mysqlnd
      - openldap
      - openldap-clients
      - openldap-devel
      - php-ldap
      - php56-php-ldap
      - phpldapadmin
      - php-mbstring
      - php56-php-mbstring
      - gd
      - gd-devel
      - php-gd
      - php56-php-gd
      - tidy
      - libtidy
      - libtidy-devel
      - php-tidy
      - php56-php-tidy
      - php-pecl-crypto
      - php56-php-pecl-crypto
      - intltool
      - php-intl
      - php56-php-intl
      - curl
      - libcurl
      - libcurl-devel
      - vsftpd
      - java-1.8.0-openjdk
      - elasticsearch
      - python3-dns
      - python3-py3dns
      - mariadb-backup
      - cyrus-sasl-devel
      - libtool-ltdl-devel
      - openssl-devel
      - libdb-devel
      - make
      - libtool
      - autoconf
      - gcc
      - perl
      - perl-devel
      - GeoIP-devel
      - GeoIP
      - GeoIP-GeoLite-data
      - GeoIP-GeoLite-data-extra
      - php-pecl-geoip
      - php56-php-pecl-geoip
      - php-pecl-pam
      - php74-php-pecl-pam
      - libgweather
      - libgweather-devel
      - cyrus-sasl-ldap
      - mod_ldap
      - openssh-ldap
      - openssh-ldap-authkeys
      - postfix-ldap
      - sssd-ldap
      - 389-ds-base
      - fortune-mod
      # - mongodb-org
      - fail2ban-all
      - fail2ban-firewalld
      - fail2ban-selinux
      - fail2ban-sendmail
      - fail2ban-server
      - fail2ban-systemd
      - fail2ban
    state: latest
- name: Install Horde packages
  dnf:
    name:
      - php-channel-horde
      - php-horde-Horde-Alarm
      - php-horde-Horde-Argv
      - php-horde-Horde-Auth
      - php-horde-Horde-Autoloader
      - php-horde-Horde-Browser
      - php-horde-Horde-Cache
      - php-horde-Horde-Cli
      - php-horde-Horde-Compress
      - php-horde-Horde-Core
      - php-horde-Horde-Crypt
      - php-horde-Horde-Dav
      - php-horde-Horde-Db
      - php-horde-Horde-Editor
      - php-horde-Horde-ElasticSearch
      - php-horde-Horde-Http
      - php-horde-Horde-Image
      - php-horde-Horde-Imap-Client
      - php-horde-Horde-Ldap
      - php-horde-Horde-ListHeaders
      - php-horde-Horde-Log
      - php-horde-Horde-Mail
      - php-horde-Horde-Mail-Autoconfig
      - php-horde-Horde-Memcache
      - php-horde-Horde-Mime
      - php-horde-Horde-Mime-Viewer
      - php-horde-Horde-Notification
      - php-horde-Horde-Oauth
      - php-horde-Horde-Pdf
      - php-horde-Horde-Perms
      - php-horde-Horde-Prefs
      - php-horde-Horde-Role
      - php-horde-Horde-Routes
      - php-horde-Horde-Rpc
      - php-horde-Horde-Service-Weather
      - php-horde-Horde-Smtp
      - php-horde-Horde-Socket-Client
      - php-horde-Horde-SyncMl
      - php-horde-Horde-Template
      - php-horde-Horde-Test
      - php-horde-Horde-Text-Filter
      - php-horde-Horde-Text-Filter-Csstidy
      - php-horde-Horde-Text-Flowed
      - php-horde-Horde-Tree
      - php-horde-Horde-Url
      - php-horde-Horde-Util
      - php-horde-Horde-View
      - php-horde-Horde-Xml-Element
      - php-horde-horde
      - php-horde-passwd
      - php-horde-Horde-Compress-Fast
      - php-horde-Horde-Crypt-Blowfish
      - php-horde-Horde-Icalendar
      - php-horde-Horde-Itip
      - php-horde-Horde-Mapi
      - php-horde-Horde-OpenXchange
      - php-horde-Horde-Secret
      - php-horde-Horde-Service-Gravatar
      - php-horde-Horde-Text-Diff
      - php-horde-Horde-Timezone
      - php-horde-Horde-Vfs
      - php-horde-imp
      - php-horde-kronolith
      - php-horde-turba
      # - php-horde-Horde-Mongo
      - php-horde-ingo
      - php-horde-mnemo
      - php-horde-wicked
    enablerepo: remi
    state: latest
