---
- name: "Set up ACME challenge TXT records for {{ challenge_item.key }}"
  import_tasks: add_dns_record.yml
  vars:
    record:
      zone: "{{ challenge_item.key|replace('*.', '') }}"
      name: "{{ challenge_item.value['dns-01'].resource }}"
      type: TXT
      content: "{{ challenge_item.value['dns-01'].resource_value }}"
      ttl: 60
      append: yes
  when: 'public_dns == "yes"'
- name: Reload PowerDNS config
  ansible.builtin.systemd_service:
    name: pdns
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: 'public_dns == "yes"'
- name: "Warn user to set up TXT records with the Let's Encrypt challenge for {{ challenge_item.key }}"
  debug:
    msg:
      - ""
      - "Please, set up the following TXT record with your DNS provider if not done yet:"
      - "==============================================================================="
      - ""
      - "domain: {{ challenge_item.key }}"
      - "record: {{ challenge_item.value['dns-01'].record }}"
      - "type: TXT"
      - "ttl: 60"
      - "value: {{ challenge_item.value['dns-01'].resource_value }}"
      - ""
  until: "challenge_item.value['dns-01'].resource_value in lookup('community.general.dig', challenge_item.value['dns-01'].record ~ './TXT')|split(',')"
  retries: 60
  delay: 60
