- name: "Warn user to set up {{ item.value['dns-01'].record }} TXT record with the Letsencrypt challenge"
  debug:
    msg:
      - ""
      - "Please, set up the following TXT record with your DNS provider if not done yet:"
      - "==============================================================================="
      - ""
      - "domain: {{ item.key }}"
      - "record: {{ item.value['dns-01'].record }}"
      - "type: TXT"
      - "ttl: 60"
      - "value: {{ item.value['dns-01'].resource_value }}"
      - ""
  with_dict: "{{ letsencrypt_challenge.challenge_data }}"
  when: "{{ (item.value['dns-01'].resource ~ '.' ~ domain_item) == item.value['dns-01'].record and item.value['dns-01'].resource_value != lookup('community.general.dig', item.value['dns-01'].record ~ './TXT') }}"
- name: "Wait for {{ item.value['dns-01'].record }} TXT record to get propagated"
  community.dns.wait_for_txt:
    records:
      - name: "{{ item.value['dns-01'].record }}"
        values: "{{ item.value['dns-01'].resource_value }}"
        mode: equals
    always_ask_default_resolver: no
  with_dict: "{{ letsencrypt_challenge.challenge_data }}"
  when: "{{ (item.value['dns-01'].resource ~ '.' ~ domain_item) == item.value['dns-01'].record }}"
