- name: "Set up ACME challenge TXT records for {{ domain_item }}"
  lineinfile:
    path: /etc/dnsmasq.conf
    regex: "txt-record={{ item.value['dns-01'].record }}"
    line: "txt-record={{ item.value['dns-01'].record }},\"{{ item.value['dns-01'].resource_value }}\""
    mode: u=rw,og=r
    owner: root
    group: dnsmasq
    state: present
    backup: yes
  with_dict: "{{ letsencrypt_challenge.challenge_data }}"
  when: 'public_dns == "yes"'
- name: Reload DNSMASQ config
  systemd:
    name: dnsmasq
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: 'public_dns == "yes"'
- name: "Warn user to set up TXT records with the Let's Encrypt challenge for {{ domain_item }}"
  debug:
    msg:
      - ""
      - "Please, set up the following TXT record with your DNS provider if not done yet:"
      - "==============================================================================="
      - ""
      - "domain: {{ item.key }}"
      - "record: {{ item.value['dns-01'].record }}"
      - "type: TXT"
      - "ttl: 60"
      - "value: {{ item.value['dns-01'].resource_value }}"
      - ""
  with_dict: "{{ letsencrypt_challenge.challenge_data }}"
  when: "{{ (item.value['dns-01'].resource ~ '.' ~ domain_item) == item.value['dns-01'].record and item.value['dns-01'].resource_value != lookup('community.general.dig', item.value['dns-01'].record ~ './TXT') }}"
- name: "Wait for TXT record to get propagated"
  community.dns.wait_for_txt:
    records:
      - name: "{{ item.value['dns-01'].record }}"
        values: "{{ item.value['dns-01'].resource_value }}"
        mode: equals
    always_ask_default_resolver: no
  with_dict: "{{ letsencrypt_challenge.challenge_data }}"
  when: "{{ (item.value['dns-01'].resource ~ '.' ~ domain_item) == item.value['dns-01'].record }}"
