- name: "Stop {{ service }}"
  systemd:
    name: "{{ service }}"
    daemon_reload: yes
    enabled: yes
    state: stopped
- name: "Restore {{ service }} backup"
  when: service_backup_path is defined
  unarchive:
    src: "{{ service_backup_path }}"
    dest: /
    remote_src: yes
- name: "Start {{ service }}"
  systemd:
    name: "{{ service }}"
    daemon_reload: yes
    enabled: yes
    state: started
