- name: Configure SPAMAssassin options
  lineinfile:
    regexp: 'SPAMDOPTIONS'
    line: SPAMDOPTIONS="-c -m5 -H --razor-home-dir='/var/lib/razor/' --razor-log-file='sys-syslog' --no-user-config --virtual-config-dir=/var/vmail/%d/%l/spamassassin --username=vmail"
    path: /etc/sysconfig/spamassassin
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
- name: Configure SPAMAssassin milter flags
  lineinfile:
    regexp: 'EXTRA_FLAGS'
    line: 'EXTRA_FLAGS=" -e {{ mailserver_domain }} -u sa-milt -m -r 8 -R SPAM_ARE_NOT_ALLOWED_HERE -i 127.0.0.1 -g sa-milt -- --max-size=52428800"'
    path: /etc/sysconfig/spamass-milter
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
- name: Add Postfix user to the sa-milt group
  user:
    name: postfix
    groups: sa-milt
    append: yes
- name: Configure SPAMAssassin rules
  lineinfile:
    regexp: '{{ item.type }} {{ item.key }}'
    line: '{{ item.type }} {{ item.key }}    {{ item.value }}'
    path: /etc/mail/spamassassin/local.cf
    mode: u=rw,og=r
    owner: root
    group: root
    state: present
    backup: yes
  loop: "{{ spamassassin_rules }}"
- name: Upload sieve config
  copy:
    dest: /var/mail/SpamToJunk.sieve
    src: "SpamToJunk.sieve"
    mode: u=rw,og=r
    backup: yes
    owner: root
    group: root
- name: Enable sieve config
  command: sievec /var/mail/SpamToJunk.sieve
  args:
    creates: /var/mail/SpamToJunk.svbin
