- name: Request Let's Encrypt certificates
  command: 'certbot --apache --agree-tos --staple-ocsp --email {{ ssl_admin_email }} -d {{ ([mailserver_domain] + [mailserver_hostname] + ["postfixadmin." ~ mailserver_domain] + custom_domains)|join(",") }} --noninteractive --redirect --hsts{{ " --test-cert" if production is not defined or not production }}'
  args:
    creates: "/etc/letsencrypt/live/{{ mailserver_hostname }}"
- name: Generate OpenSSL DHParam
  openssl_dhparam:
    path: /etc/dovecot/dh.pem
    size: 4096
    mode: u=rw,og=r
    backup: yes
    owner: root
    group: root
- name: Auto-renew certificates
  cron:
    name: certbot
    special_time: daily
    job: "certbot renew --quiet && systemctl reload postfix dovecot httpd"
    backup: yes
