---
- name: Create OS users
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') | default(lookup('password', '/tmp/ansible-mailserver-install.' + item.name + '_password chars=ascii_letters,digits,punctuation')) }}"
    groups: "{{ 'wheel' if item.name == mailserver_admin_user }}"
    append: yes
    state: present
  loop: "{{ users }}"
  register: user_info
  no_log: yes
  notify: Warn on passwords
  tags:
    - all
    - ftp
    - httpd
    - poweradmin
    - wireguard
    - dns
    - ldap
    # - postfixadmin
    - users
