---
- name: Render WebDav web config templates
  tags:
    - dyndns
    - wireguard
    - webdav
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: u=rw,og=r
    owner: root
    group: root
    backup: yes
  loop:
    - { src: "httpd/webdav.conf.j2", dest: "/etc/httpd/conf.d/401-webdav.{{ mailserver_domain }}.conf" }
    - { src: "httpd/webdav-le-ssl.conf.j2", dest: "/etc/httpd/conf.d/401-webdav.{{ mailserver_domain }}-le-ssl.conf" }
  notify: Restart httpd
- name: Create WebDAV directory
  tags: wireguard
  ansible.builtin.file:
    path: /var/www/html/webdav
    state: directory
    owner: apache
    group: apache
    mode: u=rwX,og=rX
- name: Ensure WebDav certificate directory exists
  tags: ssl
  ansible.builtin.file:
    path: /var/www/html/webdav/.certificates
    owner: apache
    group: apache
    state: directory
    mode: ug=rwX,o=rX
  become: true
  become_user: apache
- name: BindFS mount SSL certificates to WebDav
  tags: ssl
  ansible.posix.mount:
    path: /var/www/html/webdav/.certificates
    src: /etc/letsencrypt/certificates
    opts: map=root/apache:@root/@apache,perms=u=rwX:g=rwX,
    state: mounted
    fstype: fuse.bindfs
- name: Set up SELinux rules for WebDAV
  tags: wireguard
  when: getenforce.stdout != 'Disabled'
  block:
    - name: Set SELinux context on WebDAV directory
      community.general.sefcontext:
        target: '/var/www/html/webdav(/.*)?'
        setype: httpd_sys_rw_content_t
        state: present
    - name: Apply SELinux file context on WebDAV directory
      ansible.builtin.command: restorecon -irv /var/www/html/webdav
      register: restore_webdav_selinux_context
      changed_when: restore_webdav_selinux_context.rc == 0
