---
- name: Open firewall
  include: firewall.yml
  vars:
    port: "{{ wireguard.listen_port }}/udp"
- name: Load kernel modules
  lineinfile:
    path: "/etc/modules-load.d/{{ item }}.conf"
    line: "{{ item }}"
    create: yes
    backup: yes
- name: Set sysctl variables
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present # not required. choices: present;absent. Whether the entry should be present or absent in the sysctl file.
    ignoreerrors: no # not required. Use this option to ignore errors about unknown keys.
    reload: yes # not required. If C(yes), performs a I(/sbin/sysctl -p) if the C(sysctl_file) is updated. If C(no), does not reload I(sysctl) even if the C(sysctl_file) is updated.
    sysctl_set: yes
  loop:
    - "net.ipv4.ip_forward"
    - "net.ipv6.conf.all.forwarding"
- name: Create subspace config directory
  file:
    path: /etc/subspace
    state: directory
- name: Deploy docker-compose.yaml
  template:
    src: subspace/docker-compose.yaml.j2
    dest: /etc/subspace/docker-compose.yaml
    backup: true
- name: Create subspace container
  docker_compose:
    project_name: subspace
    project_src: /etc/subspace
    build: yes
    pull: yes
